# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumeRebate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumeRebate.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x63onsumeRebate.proto\"~\n\x11\x43onsumeRebateInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x61\x63tId\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x0f\n\x07\x63onsume\x18\x04 \x01(\x05\x12\x0e\n\x06reward\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\x05\x12\r\n\x05level\x18\x07 \x01(\x05')
)




_CONSUMEREBATEINFO = _descriptor.Descriptor(
  name='ConsumeRebateInfo',
  full_name='ConsumeRebateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ConsumeRebateInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actId', full_name='ConsumeRebateInfo.actId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ConsumeRebateInfo.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consume', full_name='ConsumeRebateInfo.consume', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='ConsumeRebateInfo.reward', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ConsumeRebateInfo.status', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='ConsumeRebateInfo.level', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['ConsumeRebateInfo'] = _CONSUMEREBATEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsumeRebateInfo = _reflection.GeneratedProtocolMessageType('ConsumeRebateInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMEREBATEINFO,
  __module__ = 'consumeRebate_pb2'
  # @@protoc_insertion_point(class_scope:ConsumeRebateInfo)
  ))
_sym_db.RegisterMessage(ConsumeRebateInfo)


# @@protoc_insertion_point(module_scope)
