# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: footballfacilities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gameTeamInfo_pb2 as gameTeamInfo__pb2
import gameProperty_pb2 as gameProperty__pb2
import gameUserFacility_pb2 as gameUserFacility__pb2
import subcourtInfo_pb2 as subcourtInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='footballfacilities.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x66ootballfacilities.proto\x1a\x12gameTeamInfo.proto\x1a\x12gameProperty.proto\x1a\x16gameUserFacility.proto\x1a\x12subcourtInfo.proto\"\x14\n\x12\x43\x32GS_GetFacilities\"`\n\x12GS2C_GetFacilities\x12%\n\nfacilities\x18\x01 \x03(\x0b\x32\x11.GameUserFacility\x12#\n\x0csubcourtInfo\x18\x02 \x03(\x0b\x32\r.SubcourtInfo\" \n\x10\x43\x32GS_GetFacility\x12\x0c\n\x04type\x18\x01 \x01(\x05\"9\n\x10GS2C_GetFacility\x12%\n\nfacilities\x18\x01 \x01(\x0b\x32\x11.GameUserFacility\"&\n\x16\x43\x32GS_UpgradeFacilities\x12\x0c\n\x04type\x18\x01 \x02(\x05\"b\n\x16GS2C_UpgradeFacilities\x12#\n\x08\x66\x61\x63ility\x18\x01 \x02(\x0b\x32\x11.GameUserFacility\x12#\n\x0cgameTeamInfo\x18\x02 \x01(\x0b\x32\r.GameTeamInfo\")\n\x19\x43\x32GS_UpgradeQuicklyFinish\x12\x0c\n\x04type\x18\x01 \x02(\x05\"e\n\x19GS2C_UpgradeQuicklyFinish\x12#\n\x08\x66\x61\x63ility\x18\x01 \x02(\x0b\x32\x11.GameUserFacility\x12#\n\x0cgameTeamInfo\x18\x02 \x02(\x0b\x32\r.GameTeamInfo')
  ,
  dependencies=[gameTeamInfo__pb2.DESCRIPTOR,gameProperty__pb2.DESCRIPTOR,gameUserFacility__pb2.DESCRIPTOR,subcourtInfo__pb2.DESCRIPTOR,])




_C2GS_GETFACILITIES = _descriptor.Descriptor(
  name='C2GS_GetFacilities',
  full_name='C2GS_GetFacilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=132,
)


_GS2C_GETFACILITIES = _descriptor.Descriptor(
  name='GS2C_GetFacilities',
  full_name='GS2C_GetFacilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='facilities', full_name='GS2C_GetFacilities.facilities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subcourtInfo', full_name='GS2C_GetFacilities.subcourtInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=230,
)


_C2GS_GETFACILITY = _descriptor.Descriptor(
  name='C2GS_GetFacility',
  full_name='C2GS_GetFacility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GS_GetFacility.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=264,
)


_GS2C_GETFACILITY = _descriptor.Descriptor(
  name='GS2C_GetFacility',
  full_name='GS2C_GetFacility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='facilities', full_name='GS2C_GetFacility.facilities', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=323,
)


_C2GS_UPGRADEFACILITIES = _descriptor.Descriptor(
  name='C2GS_UpgradeFacilities',
  full_name='C2GS_UpgradeFacilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GS_UpgradeFacilities.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=363,
)


_GS2C_UPGRADEFACILITIES = _descriptor.Descriptor(
  name='GS2C_UpgradeFacilities',
  full_name='GS2C_UpgradeFacilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='facility', full_name='GS2C_UpgradeFacilities.facility', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='GS2C_UpgradeFacilities.gameTeamInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=463,
)


_C2GS_UPGRADEQUICKLYFINISH = _descriptor.Descriptor(
  name='C2GS_UpgradeQuicklyFinish',
  full_name='C2GS_UpgradeQuicklyFinish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GS_UpgradeQuicklyFinish.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=506,
)


_GS2C_UPGRADEQUICKLYFINISH = _descriptor.Descriptor(
  name='GS2C_UpgradeQuicklyFinish',
  full_name='GS2C_UpgradeQuicklyFinish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='facility', full_name='GS2C_UpgradeQuicklyFinish.facility', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='GS2C_UpgradeQuicklyFinish.gameTeamInfo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=609,
)

_GS2C_GETFACILITIES.fields_by_name['facilities'].message_type = gameUserFacility__pb2._GAMEUSERFACILITY
_GS2C_GETFACILITIES.fields_by_name['subcourtInfo'].message_type = subcourtInfo__pb2._SUBCOURTINFO
_GS2C_GETFACILITY.fields_by_name['facilities'].message_type = gameUserFacility__pb2._GAMEUSERFACILITY
_GS2C_UPGRADEFACILITIES.fields_by_name['facility'].message_type = gameUserFacility__pb2._GAMEUSERFACILITY
_GS2C_UPGRADEFACILITIES.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
_GS2C_UPGRADEQUICKLYFINISH.fields_by_name['facility'].message_type = gameUserFacility__pb2._GAMEUSERFACILITY
_GS2C_UPGRADEQUICKLYFINISH.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
DESCRIPTOR.message_types_by_name['C2GS_GetFacilities'] = _C2GS_GETFACILITIES
DESCRIPTOR.message_types_by_name['GS2C_GetFacilities'] = _GS2C_GETFACILITIES
DESCRIPTOR.message_types_by_name['C2GS_GetFacility'] = _C2GS_GETFACILITY
DESCRIPTOR.message_types_by_name['GS2C_GetFacility'] = _GS2C_GETFACILITY
DESCRIPTOR.message_types_by_name['C2GS_UpgradeFacilities'] = _C2GS_UPGRADEFACILITIES
DESCRIPTOR.message_types_by_name['GS2C_UpgradeFacilities'] = _GS2C_UPGRADEFACILITIES
DESCRIPTOR.message_types_by_name['C2GS_UpgradeQuicklyFinish'] = _C2GS_UPGRADEQUICKLYFINISH
DESCRIPTOR.message_types_by_name['GS2C_UpgradeQuicklyFinish'] = _GS2C_UPGRADEQUICKLYFINISH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2GS_GetFacilities = _reflection.GeneratedProtocolMessageType('C2GS_GetFacilities', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETFACILITIES,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetFacilities)
  ))
_sym_db.RegisterMessage(C2GS_GetFacilities)

GS2C_GetFacilities = _reflection.GeneratedProtocolMessageType('GS2C_GetFacilities', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETFACILITIES,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetFacilities)
  ))
_sym_db.RegisterMessage(GS2C_GetFacilities)

C2GS_GetFacility = _reflection.GeneratedProtocolMessageType('C2GS_GetFacility', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETFACILITY,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetFacility)
  ))
_sym_db.RegisterMessage(C2GS_GetFacility)

GS2C_GetFacility = _reflection.GeneratedProtocolMessageType('GS2C_GetFacility', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETFACILITY,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetFacility)
  ))
_sym_db.RegisterMessage(GS2C_GetFacility)

C2GS_UpgradeFacilities = _reflection.GeneratedProtocolMessageType('C2GS_UpgradeFacilities', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_UPGRADEFACILITIES,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_UpgradeFacilities)
  ))
_sym_db.RegisterMessage(C2GS_UpgradeFacilities)

GS2C_UpgradeFacilities = _reflection.GeneratedProtocolMessageType('GS2C_UpgradeFacilities', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_UPGRADEFACILITIES,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_UpgradeFacilities)
  ))
_sym_db.RegisterMessage(GS2C_UpgradeFacilities)

C2GS_UpgradeQuicklyFinish = _reflection.GeneratedProtocolMessageType('C2GS_UpgradeQuicklyFinish', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_UPGRADEQUICKLYFINISH,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_UpgradeQuicklyFinish)
  ))
_sym_db.RegisterMessage(C2GS_UpgradeQuicklyFinish)

GS2C_UpgradeQuicklyFinish = _reflection.GeneratedProtocolMessageType('GS2C_UpgradeQuicklyFinish', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_UPGRADEQUICKLYFINISH,
  __module__ = 'footballfacilities_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_UpgradeQuicklyFinish)
  ))
_sym_db.RegisterMessage(GS2C_UpgradeQuicklyFinish)


# @@protoc_insertion_point(module_scope)
