# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameUserTacticsInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameUserTacticsInfo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19gameUserTacticsInfo.proto\"\xf4\x01\n\x13GameUserTacticsInfo\x12\x11\n\ttacticsId\x18\x01 \x01(\x05\x12\x14\n\x0c\x61ttackRegion\x18\x02 \x01(\x05\x12\x13\n\x0b\x61ttackTrend\x18\x03 \x01(\x05\x12\x14\n\x0c\x61ttackRhythm\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x65\x66\x65ndRegion\x18\x05 \x01(\x05\x12\x16\n\x0e\x64\x65\x66\x65ndStrategy\x18\x06 \x01(\x05\x12\x18\n\x10\x61ggressIntension\x18\x07 \x01(\x05\x12\x18\n\x10organizationForm\x18\x08 \x01(\x05\x12\x14\n\x0cpassingTypes\x18\t \x01(\x05\x12\x11\n\tcooperate\x18\n \x01(\x05')
)




_GAMEUSERTACTICSINFO = _descriptor.Descriptor(
  name='GameUserTacticsInfo',
  full_name='GameUserTacticsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tacticsId', full_name='GameUserTacticsInfo.tacticsId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attackRegion', full_name='GameUserTacticsInfo.attackRegion', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attackTrend', full_name='GameUserTacticsInfo.attackTrend', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attackRhythm', full_name='GameUserTacticsInfo.attackRhythm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defendRegion', full_name='GameUserTacticsInfo.defendRegion', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defendStrategy', full_name='GameUserTacticsInfo.defendStrategy', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggressIntension', full_name='GameUserTacticsInfo.aggressIntension', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationForm', full_name='GameUserTacticsInfo.organizationForm', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passingTypes', full_name='GameUserTacticsInfo.passingTypes', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cooperate', full_name='GameUserTacticsInfo.cooperate', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=274,
)

DESCRIPTOR.message_types_by_name['GameUserTacticsInfo'] = _GAMEUSERTACTICSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameUserTacticsInfo = _reflection.GeneratedProtocolMessageType('GameUserTacticsInfo', (_message.Message,), dict(
  DESCRIPTOR = _GAMEUSERTACTICSINFO,
  __module__ = 'gameUserTacticsInfo_pb2'
  # @@protoc_insertion_point(class_scope:GameUserTacticsInfo)
  ))
_sym_db.RegisterMessage(GameUserTacticsInfo)


# @@protoc_insertion_point(module_scope)
