# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameCommonDaySignInPackage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameCommonDaySignInPackage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n gameCommonDaySignInPackage.proto\"L\n\x1aGameCommonDaySignInPackage\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05\x12\x11\n\tpackageId\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\x05')
)




_GAMECOMMONDAYSIGNINPACKAGE = _descriptor.Descriptor(
  name='GameCommonDaySignInPackage',
  full_name='GameCommonDaySignInPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='GameCommonDaySignInPackage.day', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageId', full_name='GameCommonDaySignInPackage.packageId', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GameCommonDaySignInPackage.status', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['GameCommonDaySignInPackage'] = _GAMECOMMONDAYSIGNINPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameCommonDaySignInPackage = _reflection.GeneratedProtocolMessageType('GameCommonDaySignInPackage', (_message.Message,), dict(
  DESCRIPTOR = _GAMECOMMONDAYSIGNINPACKAGE,
  __module__ = 'gameCommonDaySignInPackage_pb2'
  # @@protoc_insertion_point(class_scope:GameCommonDaySignInPackage)
  ))
_sym_db.RegisterMessage(GameCommonDaySignInPackage)


# @@protoc_insertion_point(module_scope)
