# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamePlayerResponsibility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamePlayerResponsibility.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1egamePlayerResponsibility.proto\":\n\x18GamePlayerResponsibility\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05')
)




_GAMEPLAYERRESPONSIBILITY = _descriptor.Descriptor(
  name='GamePlayerResponsibility',
  full_name='GamePlayerResponsibility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GamePlayerResponsibility.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='GamePlayerResponsibility.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['GamePlayerResponsibility'] = _GAMEPLAYERRESPONSIBILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GamePlayerResponsibility = _reflection.GeneratedProtocolMessageType('GamePlayerResponsibility', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPLAYERRESPONSIBILITY,
  __module__ = 'gamePlayerResponsibility_pb2'
  # @@protoc_insertion_point(class_scope:GamePlayerResponsibility)
  ))
_sym_db.RegisterMessage(GamePlayerResponsibility)


# @@protoc_insertion_point(module_scope)
