# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameUserFacility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameUserFacility.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16gameUserFacility.proto\"G\n\x10GameUserFacility\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\r\n\x05level\x18\x02 \x02(\x05\x12\x16\n\x0eupgradeEndTime\x18\x03 \x01(\x05')
)




_GAMEUSERFACILITY = _descriptor.Descriptor(
  name='GameUserFacility',
  full_name='GameUserFacility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GameUserFacility.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='GameUserFacility.level', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upgradeEndTime', full_name='GameUserFacility.upgradeEndTime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['GameUserFacility'] = _GAMEUSERFACILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameUserFacility = _reflection.GeneratedProtocolMessageType('GameUserFacility', (_message.Message,), dict(
  DESCRIPTOR = _GAMEUSERFACILITY,
  __module__ = 'gameUserFacility_pb2'
  # @@protoc_insertion_point(class_scope:GameUserFacility)
  ))
_sym_db.RegisterMessage(GameUserFacility)


# @@protoc_insertion_point(module_scope)
