# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamePlayerInstanceBase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import playerZhanli_pb2 as playerZhanli__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamePlayerInstanceBase.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1cgamePlayerInstanceBase.proto\x1a\x12playerZhanli.proto\"\xab\x05\n\x16GamePlayerInstanceBase\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ommonPlayerId\x18\x02 \x01(\x05\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x0e\n\x06tineng\x18\x04 \x01(\x05\x12\x11\n\tzhuangtai\x18\x05 \x01(\x05\x12\x11\n\tshangbing\x18\x06 \x01(\x05\x12\x0e\n\x06status\x18\x07 \x01(\x05\x12\x0c\n\x04star\x18\x08 \x01(\x05\x12 \n\x18tacitUnderstandingLevel1\x18\x15 \x01(\x05\x12\x1e\n\x16tacitUnderstandingExp1\x18\x16 \x01(\x05\x12 \n\x18tacitUnderstandingLevel2\x18\x18 \x01(\x05\x12\x1e\n\x16tacitUnderstandingExp2\x18\x19 \x01(\x05\x12 \n\x18tacitUnderstandingLevel3\x18\x1a \x01(\x05\x12\x1e\n\x16tacitUnderstandingExp3\x18\x1b \x01(\x05\x12 \n\x18tacitUnderstandingLevel4\x18\x1c \x01(\x05\x12\x1e\n\x16tacitUnderstandingExp4\x18\x1d \x01(\x05\x12\x11\n\tgradation\x18\t \x01(\x05\x12\r\n\x05level\x18\n \x01(\x05\x12\x13\n\x0bskill1Grade\x18\x0b \x01(\x05\x12\x13\n\x0bskill2Grade\x18\x0c \x01(\x05\x12\x13\n\x0bskill3Grade\x18\r \x01(\x05\x12\x14\n\x0cserialNumber\x18\x0e \x01(\x05\x12\x11\n\texprience\x18\x0f \x01(\x05\x12\x14\n\x0cshangbingDay\x18\x10 \x01(\x05\x12\x15\n\rshangbingTime\x18\x11 \x01(\x03\x12\x11\n\treplyTime\x18\x12 \x01(\x03\x12\x10\n\x08gainTime\x18\x13 \x01(\x03\x12\x0f\n\x07isShoot\x18\x14 \x01(\x05\x12\x11\n\tnewPlayer\x18\x17 \x01(\x05')
  ,
  dependencies=[playerZhanli__pb2.DESCRIPTOR,])




_GAMEPLAYERINSTANCEBASE = _descriptor.Descriptor(
  name='GamePlayerInstanceBase',
  full_name='GamePlayerInstanceBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='GamePlayerInstanceBase.playerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commonPlayerId', full_name='GamePlayerInstanceBase.commonPlayerId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='GamePlayerInstanceBase.uid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tineng', full_name='GamePlayerInstanceBase.tineng', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zhuangtai', full_name='GamePlayerInstanceBase.zhuangtai', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shangbing', full_name='GamePlayerInstanceBase.shangbing', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GamePlayerInstanceBase.status', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='star', full_name='GamePlayerInstanceBase.star', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingLevel1', full_name='GamePlayerInstanceBase.tacitUnderstandingLevel1', index=8,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingExp1', full_name='GamePlayerInstanceBase.tacitUnderstandingExp1', index=9,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingLevel2', full_name='GamePlayerInstanceBase.tacitUnderstandingLevel2', index=10,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingExp2', full_name='GamePlayerInstanceBase.tacitUnderstandingExp2', index=11,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingLevel3', full_name='GamePlayerInstanceBase.tacitUnderstandingLevel3', index=12,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingExp3', full_name='GamePlayerInstanceBase.tacitUnderstandingExp3', index=13,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingLevel4', full_name='GamePlayerInstanceBase.tacitUnderstandingLevel4', index=14,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tacitUnderstandingExp4', full_name='GamePlayerInstanceBase.tacitUnderstandingExp4', index=15,
      number=29, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gradation', full_name='GamePlayerInstanceBase.gradation', index=16,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='GamePlayerInstanceBase.level', index=17,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill1Grade', full_name='GamePlayerInstanceBase.skill1Grade', index=18,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill2Grade', full_name='GamePlayerInstanceBase.skill2Grade', index=19,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill3Grade', full_name='GamePlayerInstanceBase.skill3Grade', index=20,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='GamePlayerInstanceBase.serialNumber', index=21,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exprience', full_name='GamePlayerInstanceBase.exprience', index=22,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shangbingDay', full_name='GamePlayerInstanceBase.shangbingDay', index=23,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shangbingTime', full_name='GamePlayerInstanceBase.shangbingTime', index=24,
      number=17, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replyTime', full_name='GamePlayerInstanceBase.replyTime', index=25,
      number=18, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gainTime', full_name='GamePlayerInstanceBase.gainTime', index=26,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isShoot', full_name='GamePlayerInstanceBase.isShoot', index=27,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newPlayer', full_name='GamePlayerInstanceBase.newPlayer', index=28,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=736,
)

DESCRIPTOR.message_types_by_name['GamePlayerInstanceBase'] = _GAMEPLAYERINSTANCEBASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GamePlayerInstanceBase = _reflection.GeneratedProtocolMessageType('GamePlayerInstanceBase', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPLAYERINSTANCEBASE,
  __module__ = 'gamePlayerInstanceBase_pb2'
  # @@protoc_insertion_point(class_scope:GamePlayerInstanceBase)
  ))
_sym_db.RegisterMessage(GamePlayerInstanceBase)


# @@protoc_insertion_point(module_scope)
