# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameUserChampionRoad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameUserChampionRoad.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1agameUserChampionRoad.proto\"w\n\x14GameUserChampionRoad\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x16\n\x0e\x63hallengeCount\x18\x02 \x02(\x05\x12\x19\n\x11passedCheckPoints\x18\x03 \x02(\x05\x12 \n\x18perfectPassedCheckPoints\x18\x04 \x03(\x05')
)




_GAMEUSERCHAMPIONROAD = _descriptor.Descriptor(
  name='GameUserChampionRoad',
  full_name='GameUserChampionRoad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GameUserChampionRoad.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challengeCount', full_name='GameUserChampionRoad.challengeCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passedCheckPoints', full_name='GameUserChampionRoad.passedCheckPoints', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perfectPassedCheckPoints', full_name='GameUserChampionRoad.perfectPassedCheckPoints', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['GameUserChampionRoad'] = _GAMEUSERCHAMPIONROAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameUserChampionRoad = _reflection.GeneratedProtocolMessageType('GameUserChampionRoad', (_message.Message,), dict(
  DESCRIPTOR = _GAMEUSERCHAMPIONROAD,
  __module__ = 'gameUserChampionRoad_pb2'
  # @@protoc_insertion_point(class_scope:GameUserChampionRoad)
  ))
_sym_db.RegisterMessage(GameUserChampionRoad)


# @@protoc_insertion_point(module_scope)
