# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamePracticeCompetition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamePracticeCompetition.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1dgamePracticeCompetition.proto\x1a\x0epropResp.proto\"\xa1\x01\n\x17GamePracticeCompetition\x12\x0c\n\x04step\x18\x01 \x02(\x05\x12\x13\n\x0b\x62ufferValue\x18\x02 \x02(\x05\x12*\n\ndailyInfos\x18\x03 \x03(\x0b\x32\x16.GamePracticeDailyInfo\x12 \n\x0b\x66inalReward\x18\x04 \x03(\x0b\x32\x0b.PropRespVo\x12\x15\n\rcompetitionId\x18\x05 \x02(\x05\"]\n\x15GamePracticeDailyInfo\x12\x15\n\rdailyDetailId\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x0e\n\x06status\x18\x03 \x02(\x05\x12\x0f\n\x07winType\x18\x04 \x01(\x05')
  ,
  dependencies=[propResp__pb2.DESCRIPTOR,])




_GAMEPRACTICECOMPETITION = _descriptor.Descriptor(
  name='GamePracticeCompetition',
  full_name='GamePracticeCompetition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='GamePracticeCompetition.step', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bufferValue', full_name='GamePracticeCompetition.bufferValue', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dailyInfos', full_name='GamePracticeCompetition.dailyInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalReward', full_name='GamePracticeCompetition.finalReward', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competitionId', full_name='GamePracticeCompetition.competitionId', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=211,
)


_GAMEPRACTICEDAILYINFO = _descriptor.Descriptor(
  name='GamePracticeDailyInfo',
  full_name='GamePracticeDailyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dailyDetailId', full_name='GamePracticeDailyInfo.dailyDetailId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='GamePracticeDailyInfo.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GamePracticeDailyInfo.status', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winType', full_name='GamePracticeDailyInfo.winType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=306,
)

_GAMEPRACTICECOMPETITION.fields_by_name['dailyInfos'].message_type = _GAMEPRACTICEDAILYINFO
_GAMEPRACTICECOMPETITION.fields_by_name['finalReward'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['GamePracticeCompetition'] = _GAMEPRACTICECOMPETITION
DESCRIPTOR.message_types_by_name['GamePracticeDailyInfo'] = _GAMEPRACTICEDAILYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GamePracticeCompetition = _reflection.GeneratedProtocolMessageType('GamePracticeCompetition', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPRACTICECOMPETITION,
  __module__ = 'gamePracticeCompetition_pb2'
  # @@protoc_insertion_point(class_scope:GamePracticeCompetition)
  ))
_sym_db.RegisterMessage(GamePracticeCompetition)

GamePracticeDailyInfo = _reflection.GeneratedProtocolMessageType('GamePracticeDailyInfo', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPRACTICEDAILYINFO,
  __module__ = 'gamePracticeCompetition_pb2'
  # @@protoc_insertion_point(class_scope:GamePracticeDailyInfo)
  ))
_sym_db.RegisterMessage(GamePracticeDailyInfo)


# @@protoc_insertion_point(module_scope)
