# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameUserDaySignIn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameUserDaySignIn.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17gameUserDaySignIn.proto\"T\n\x11GameUserDaySignIn\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x12\n\nupdateTime\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x64\x64\x44\x61y\x18\x05 \x01(\x05')
)




_GAMEUSERDAYSIGNIN = _descriptor.Descriptor(
  name='GameUserDaySignIn',
  full_name='GameUserDaySignIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='GameUserDaySignIn.day', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GameUserDaySignIn.status', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateTime', full_name='GameUserDaySignIn.updateTime', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addDay', full_name='GameUserDaySignIn.addDay', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['GameUserDaySignIn'] = _GAMEUSERDAYSIGNIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameUserDaySignIn = _reflection.GeneratedProtocolMessageType('GameUserDaySignIn', (_message.Message,), dict(
  DESCRIPTOR = _GAMEUSERDAYSIGNIN,
  __module__ = 'gameUserDaySignIn_pb2'
  # @@protoc_insertion_point(class_scope:GameUserDaySignIn)
  ))
_sym_db.RegisterMessage(GameUserDaySignIn)


# @@protoc_insertion_point(module_scope)
