# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameCommonDaySignIn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameCommonDaySignIn.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19gameCommonDaySignIn.proto\"G\n\x13GameCommonDaySignIn\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05\x12\x11\n\tpackageId\x18\x03 \x01(\x05\x12\x10\n\x08vipLevel\x18\x06 \x01(\x05')
)




_GAMECOMMONDAYSIGNIN = _descriptor.Descriptor(
  name='GameCommonDaySignIn',
  full_name='GameCommonDaySignIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='GameCommonDaySignIn.day', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageId', full_name='GameCommonDaySignIn.packageId', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='GameCommonDaySignIn.vipLevel', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['GameCommonDaySignIn'] = _GAMECOMMONDAYSIGNIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameCommonDaySignIn = _reflection.GeneratedProtocolMessageType('GameCommonDaySignIn', (_message.Message,), dict(
  DESCRIPTOR = _GAMECOMMONDAYSIGNIN,
  __module__ = 'gameCommonDaySignIn_pb2'
  # @@protoc_insertion_point(class_scope:GameCommonDaySignIn)
  ))
_sym_db.RegisterMessage(GameCommonDaySignIn)


# @@protoc_insertion_point(module_scope)
