# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameUserVipPackage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameUserVipPackage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x18gameUserVipPackage.proto\"0\n\x12GameUserVipPackage\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\x05')
)




_GAMEUSERVIPPACKAGE = _descriptor.Descriptor(
  name='GameUserVipPackage',
  full_name='GameUserVipPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GameUserVipPackage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='GameUserVipPackage.status', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['GameUserVipPackage'] = _GAMEUSERVIPPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameUserVipPackage = _reflection.GeneratedProtocolMessageType('GameUserVipPackage', (_message.Message,), dict(
  DESCRIPTOR = _GAMEUSERVIPPACKAGE,
  __module__ = 'gameUserVipPackage_pb2'
  # @@protoc_insertion_point(class_scope:GameUserVipPackage)
  ))
_sym_db.RegisterMessage(GameUserVipPackage)


# @@protoc_insertion_point(module_scope)
