# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goodsResp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gamePlayerInstance_pb2 as gamePlayerInstance__pb2
import gameUserEquipment_pb2 as gameUserEquipment__pb2
import gameUserDebris_pb2 as gameUserDebris__pb2
import gameProperty_pb2 as gameProperty__pb2
import gamePlayerBattle_pb2 as gamePlayerBattle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goodsResp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fgoodsResp.proto\x1a\x18gamePlayerInstance.proto\x1a\x17gameUserEquipment.proto\x1a\x14gameUserDebris.proto\x1a\x12gameProperty.proto\x1a\x16gamePlayerBattle.proto\"\xa4\x02\n\x0bGoodsRespVo\x12\'\n\nplayerList\x18\x01 \x03(\x0b\x32\x13.GamePlayerInstance\x12)\n\x10playerDebrisList\x18\x02 \x03(\x0b\x32\x0f.GameUserDebris\x12%\n\tequipList\x18\x03 \x03(\x0b\x32\x12.GameUserEquipment\x12(\n\x0f\x65quipDebrisList\x18\x04 \x03(\x0b\x32\x0f.GameUserDebris\x12#\n\x0cpropertyList\x18\x05 \x03(\x0b\x32\r.GameProperty\x12\'\n\x0cplayerBattle\x18\x06 \x03(\x0b\x32\x11.GamePlayerBattle\x12\"\n\x0bpackageList\x18\x07 \x03(\x0b\x32\r.GameProperty')
  ,
  dependencies=[gamePlayerInstance__pb2.DESCRIPTOR,gameUserEquipment__pb2.DESCRIPTOR,gameUserDebris__pb2.DESCRIPTOR,gameProperty__pb2.DESCRIPTOR,gamePlayerBattle__pb2.DESCRIPTOR,])




_GOODSRESPVO = _descriptor.Descriptor(
  name='GoodsRespVo',
  full_name='GoodsRespVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerList', full_name='GoodsRespVo.playerList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerDebrisList', full_name='GoodsRespVo.playerDebrisList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='equipList', full_name='GoodsRespVo.equipList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='equipDebrisList', full_name='GoodsRespVo.equipDebrisList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propertyList', full_name='GoodsRespVo.propertyList', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerBattle', full_name='GoodsRespVo.playerBattle', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageList', full_name='GoodsRespVo.packageList', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=429,
)

_GOODSRESPVO.fields_by_name['playerList'].message_type = gamePlayerInstance__pb2._GAMEPLAYERINSTANCE
_GOODSRESPVO.fields_by_name['playerDebrisList'].message_type = gameUserDebris__pb2._GAMEUSERDEBRIS
_GOODSRESPVO.fields_by_name['equipList'].message_type = gameUserEquipment__pb2._GAMEUSEREQUIPMENT
_GOODSRESPVO.fields_by_name['equipDebrisList'].message_type = gameUserDebris__pb2._GAMEUSERDEBRIS
_GOODSRESPVO.fields_by_name['propertyList'].message_type = gameProperty__pb2._GAMEPROPERTY
_GOODSRESPVO.fields_by_name['playerBattle'].message_type = gamePlayerBattle__pb2._GAMEPLAYERBATTLE
_GOODSRESPVO.fields_by_name['packageList'].message_type = gameProperty__pb2._GAMEPROPERTY
DESCRIPTOR.message_types_by_name['GoodsRespVo'] = _GOODSRESPVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoodsRespVo = _reflection.GeneratedProtocolMessageType('GoodsRespVo', (_message.Message,), dict(
  DESCRIPTOR = _GOODSRESPVO,
  __module__ = 'goodsResp_pb2'
  # @@protoc_insertion_point(class_scope:GoodsRespVo)
  ))
_sym_db.RegisterMessage(GoodsRespVo)


# @@protoc_insertion_point(module_scope)
