# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guildBaseInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guildBaseInfo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13guildBaseInfo.proto\"\xb5\x01\n\rGuildBaseInfo\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05level\x18\x03 \x02(\x05\x12\r\n\x05label\x18\x04 \x02(\x05\x12\r\n\x05title\x18\x05 \x02(\t\x12\x11\n\tapplyClub\x18\x06 \x02(\x05\x12\x12\n\napplyLevel\x18\x07 \x02(\x05\x12\x10\n\x08\x61pplyVip\x18\x08 \x02(\x05\x12\x11\n\tnowMember\x18\t \x02(\x05\x12\x11\n\tmaxMember\x18\n \x02(\x05')
)




_GUILDBASEINFO = _descriptor.Descriptor(
  name='GuildBaseInfo',
  full_name='GuildBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GuildBaseInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='GuildBaseInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='GuildBaseInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='GuildBaseInfo.label', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='GuildBaseInfo.title', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applyClub', full_name='GuildBaseInfo.applyClub', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applyLevel', full_name='GuildBaseInfo.applyLevel', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applyVip', full_name='GuildBaseInfo.applyVip', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nowMember', full_name='GuildBaseInfo.nowMember', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxMember', full_name='GuildBaseInfo.maxMember', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['GuildBaseInfo'] = _GUILDBASEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GuildBaseInfo = _reflection.GeneratedProtocolMessageType('GuildBaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _GUILDBASEINFO,
  __module__ = 'guildBaseInfo_pb2'
  # @@protoc_insertion_point(class_scope:GuildBaseInfo)
  ))
_sym_db.RegisterMessage(GuildBaseInfo)


# @@protoc_insertion_point(module_scope)
