# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guildExtraInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guildExtraInfo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14guildExtraInfo.proto\"y\n\x0eGuildExtraInfo\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x17\n\x0fnowContribution\x18\x02 \x02(\x05\x12\x17\n\x0fmaxContribution\x18\x03 \x02(\x05\x12)\n\x11guildTechInfoList\x18\x04 \x03(\x0b\x32\x0e.GuildTechInfo\",\n\rGuildTechInfo\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\r\n\x05level\x18\x02 \x02(\x05')
)




_GUILDEXTRAINFO = _descriptor.Descriptor(
  name='GuildExtraInfo',
  full_name='GuildExtraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GuildExtraInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nowContribution', full_name='GuildExtraInfo.nowContribution', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxContribution', full_name='GuildExtraInfo.maxContribution', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guildTechInfoList', full_name='GuildExtraInfo.guildTechInfoList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=145,
)


_GUILDTECHINFO = _descriptor.Descriptor(
  name='GuildTechInfo',
  full_name='GuildTechInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GuildTechInfo.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='GuildTechInfo.level', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=191,
)

_GUILDEXTRAINFO.fields_by_name['guildTechInfoList'].message_type = _GUILDTECHINFO
DESCRIPTOR.message_types_by_name['GuildExtraInfo'] = _GUILDEXTRAINFO
DESCRIPTOR.message_types_by_name['GuildTechInfo'] = _GUILDTECHINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GuildExtraInfo = _reflection.GeneratedProtocolMessageType('GuildExtraInfo', (_message.Message,), dict(
  DESCRIPTOR = _GUILDEXTRAINFO,
  __module__ = 'guildExtraInfo_pb2'
  # @@protoc_insertion_point(class_scope:GuildExtraInfo)
  ))
_sym_db.RegisterMessage(GuildExtraInfo)

GuildTechInfo = _reflection.GeneratedProtocolMessageType('GuildTechInfo', (_message.Message,), dict(
  DESCRIPTOR = _GUILDTECHINFO,
  __module__ = 'guildExtraInfo_pb2'
  # @@protoc_insertion_point(class_scope:GuildTechInfo)
  ))
_sym_db.RegisterMessage(GuildTechInfo)


# @@protoc_insertion_point(module_scope)
