# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginaward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import activityPackage_pb2 as activityPackage__pb2
import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loginaward.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10loginaward.proto\x1a\x15\x61\x63tivityPackage.proto\x1a\x0epropResp.proto\"\n\n\x08\x43\x32GS_Get\"\x84\x01\n\x08GS2C_Get\x12\x11\n\tstartTime\x18\x01 \x02(\t\x12\x0f\n\x07\x65ndTime\x18\x02 \x02(\t\x12\r\n\x05title\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x65sc\x18\x04 \x02(\t\x12\x0c\n\x04icon\x18\x05 \x02(\t\x12)\n\x0f\x61\x63tivityPackage\x18\x06 \x03(\x0b\x32\x10.ActivityPackage\"&\n\x13\x43\x32GS_ReceivePackage\x12\x0f\n\x07\x61wardId\x18\x01 \x02(\x05\"a\n\x13GS2C_ReceivePackage\x12)\n\x0f\x61\x63tivityPackage\x18\x01 \x03(\x0b\x32\x10.ActivityPackage\x12\x1f\n\npropRespVo\x18\x02 \x03(\x0b\x32\x0b.PropRespVo')
  ,
  dependencies=[activityPackage__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,])




_C2GS_GET = _descriptor.Descriptor(
  name='C2GS_Get',
  full_name='C2GS_Get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=69,
)


_GS2C_GET = _descriptor.Descriptor(
  name='GS2C_Get',
  full_name='GS2C_Get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTime', full_name='GS2C_Get.startTime', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='GS2C_Get.endTime', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='GS2C_Get.title', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='GS2C_Get.desc', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='GS2C_Get.icon', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activityPackage', full_name='GS2C_Get.activityPackage', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=204,
)


_C2GS_RECEIVEPACKAGE = _descriptor.Descriptor(
  name='C2GS_ReceivePackage',
  full_name='C2GS_ReceivePackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='awardId', full_name='C2GS_ReceivePackage.awardId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=244,
)


_GS2C_RECEIVEPACKAGE = _descriptor.Descriptor(
  name='GS2C_ReceivePackage',
  full_name='GS2C_ReceivePackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityPackage', full_name='GS2C_ReceivePackage.activityPackage', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='GS2C_ReceivePackage.propRespVo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=343,
)

_GS2C_GET.fields_by_name['activityPackage'].message_type = activityPackage__pb2._ACTIVITYPACKAGE
_GS2C_RECEIVEPACKAGE.fields_by_name['activityPackage'].message_type = activityPackage__pb2._ACTIVITYPACKAGE
_GS2C_RECEIVEPACKAGE.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['C2GS_Get'] = _C2GS_GET
DESCRIPTOR.message_types_by_name['GS2C_Get'] = _GS2C_GET
DESCRIPTOR.message_types_by_name['C2GS_ReceivePackage'] = _C2GS_RECEIVEPACKAGE
DESCRIPTOR.message_types_by_name['GS2C_ReceivePackage'] = _GS2C_RECEIVEPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2GS_Get = _reflection.GeneratedProtocolMessageType('C2GS_Get', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GET,
  __module__ = 'loginaward_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_Get)
  ))
_sym_db.RegisterMessage(C2GS_Get)

GS2C_Get = _reflection.GeneratedProtocolMessageType('GS2C_Get', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GET,
  __module__ = 'loginaward_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_Get)
  ))
_sym_db.RegisterMessage(GS2C_Get)

C2GS_ReceivePackage = _reflection.GeneratedProtocolMessageType('C2GS_ReceivePackage', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_RECEIVEPACKAGE,
  __module__ = 'loginaward_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_ReceivePackage)
  ))
_sym_db.RegisterMessage(C2GS_ReceivePackage)

GS2C_ReceivePackage = _reflection.GeneratedProtocolMessageType('GS2C_ReceivePackage', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_RECEIVEPACKAGE,
  __module__ = 'loginaward_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_ReceivePackage)
  ))
_sym_db.RegisterMessage(GS2C_ReceivePackage)


# @@protoc_insertion_point(module_scope)
