# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: luckyRollingAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='luckyRollingAward.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17luckyRollingAward.proto\x1a\x0epropResp.proto\"_\n\x16LuckyRollingCountAward\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05times\x18\x02 \x02(\x05\x12\x1a\n\x05\x61ward\x18\x03 \x03(\x0b\x32\x0b.PropRespVo\x12\x0e\n\x06status\x18\x04 \x02(\x05\";\n\x11LuckyRollingAward\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x1a\n\x05\x61ward\x18\x02 \x02(\x0b\x32\x0b.PropRespVo')
  ,
  dependencies=[propResp__pb2.DESCRIPTOR,])




_LUCKYROLLINGCOUNTAWARD = _descriptor.Descriptor(
  name='LuckyRollingCountAward',
  full_name='LuckyRollingCountAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LuckyRollingCountAward.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='times', full_name='LuckyRollingCountAward.times', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='award', full_name='LuckyRollingCountAward.award', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='LuckyRollingCountAward.status', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=138,
)


_LUCKYROLLINGAWARD = _descriptor.Descriptor(
  name='LuckyRollingAward',
  full_name='LuckyRollingAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LuckyRollingAward.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='award', full_name='LuckyRollingAward.award', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=199,
)

_LUCKYROLLINGCOUNTAWARD.fields_by_name['award'].message_type = propResp__pb2._PROPRESPVO
_LUCKYROLLINGAWARD.fields_by_name['award'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['LuckyRollingCountAward'] = _LUCKYROLLINGCOUNTAWARD
DESCRIPTOR.message_types_by_name['LuckyRollingAward'] = _LUCKYROLLINGAWARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LuckyRollingCountAward = _reflection.GeneratedProtocolMessageType('LuckyRollingCountAward', (_message.Message,), dict(
  DESCRIPTOR = _LUCKYROLLINGCOUNTAWARD,
  __module__ = 'luckyRollingAward_pb2'
  # @@protoc_insertion_point(class_scope:LuckyRollingCountAward)
  ))
_sym_db.RegisterMessage(LuckyRollingCountAward)

LuckyRollingAward = _reflection.GeneratedProtocolMessageType('LuckyRollingAward', (_message.Message,), dict(
  DESCRIPTOR = _LUCKYROLLINGAWARD,
  __module__ = 'luckyRollingAward_pb2'
  # @@protoc_insertion_point(class_scope:LuckyRollingAward)
  ))
_sym_db.RegisterMessage(LuckyRollingAward)


# @@protoc_insertion_point(module_scope)
