# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newPlayerCareerCheckpoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='newPlayerCareerCheckpoint.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1fnewPlayerCareerCheckpoint.proto\"j\n\x1dNewPlayerCareerCheckpointInfo\x12\x12\n\ncheckpoint\x18\x01 \x02(\x05\x12\x0c\n\x04star\x18\x02 \x02(\t\x12\x11\n\tpassCount\x18\x03 \x02(\x05\x12\x14\n\x0c\x62uyPassCount\x18\x04 \x02(\x05')
)




_NEWPLAYERCAREERCHECKPOINTINFO = _descriptor.Descriptor(
  name='NewPlayerCareerCheckpointInfo',
  full_name='NewPlayerCareerCheckpointInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkpoint', full_name='NewPlayerCareerCheckpointInfo.checkpoint', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='star', full_name='NewPlayerCareerCheckpointInfo.star', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passCount', full_name='NewPlayerCareerCheckpointInfo.passCount', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buyPassCount', full_name='NewPlayerCareerCheckpointInfo.buyPassCount', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['NewPlayerCareerCheckpointInfo'] = _NEWPLAYERCAREERCHECKPOINTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewPlayerCareerCheckpointInfo = _reflection.GeneratedProtocolMessageType('NewPlayerCareerCheckpointInfo', (_message.Message,), dict(
  DESCRIPTOR = _NEWPLAYERCAREERCHECKPOINTINFO,
  __module__ = 'newPlayerCareerCheckpoint_pb2'
  # @@protoc_insertion_point(class_scope:NewPlayerCareerCheckpointInfo)
  ))
_sym_db.RegisterMessage(NewPlayerCareerCheckpointInfo)


# @@protoc_insertion_point(module_scope)
