# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otherTeamInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import managerLable_pb2 as managerLable__pb2
import otherUserBattle_pb2 as otherUserBattle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='otherTeamInfo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13otherTeamInfo.proto\x1a\x12managerLable.proto\x1a\x15otherUserBattle.proto\"\xbd\x03\n\rOtherTeamInfo\x12\x10\n\x08\x63lubIcon\x18\x01 \x02(\x05\x12\x13\n\x0bmanagerName\x18\x02 \x02(\t\x12 \n\tlableList\x18\x03 \x01(\x0b\x32\r.ManagerLable\x12\r\n\x05level\x18\x04 \x02(\x05\x12\x12\n\nexperience\x18\x05 \x02(\x05\x12\x0e\n\x06zhanli\x18\x06 \x02(\x05\x12\x12\n\nregistDate\x18\x07 \x02(\t\x12\x0c\n\x04\x63lub\x18\x08 \x02(\x05\x12\x17\n\x0flatelyLoginTime\x18\t \x02(\x05\x12\x13\n\x0bleagueLevel\x18\n \x02(\x05\x12\x12\n\ntiantiRank\x18\x0b \x02(\t\x12\x14\n\x0c\x61\x63hieveIcon1\x18\x0c \x02(\x05\x12\x14\n\x0c\x61\x63hieveIcon2\x18\r \x02(\x05\x12\x14\n\x0c\x61\x63hieveIcon3\x18\x0e \x02(\x05\x12\x1a\n\x12homeFieldPoloShirt\x18\x0f \x02(\x05\x12\x1e\n\x16visitingFieldPoloShirt\x18\x10 \x02(\x05\x12)\n\x0fotherUserBattle\x18\x11 \x02(\x0b\x32\x10.OtherUserBattle\x12\x10\n\x08vipLevel\x18\x12 \x02(\x05\x12\x11\n\tguildName\x18\x13 \x01(\t')
  ,
  dependencies=[managerLable__pb2.DESCRIPTOR,otherUserBattle__pb2.DESCRIPTOR,])




_OTHERTEAMINFO = _descriptor.Descriptor(
  name='OtherTeamInfo',
  full_name='OtherTeamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clubIcon', full_name='OtherTeamInfo.clubIcon', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='managerName', full_name='OtherTeamInfo.managerName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lableList', full_name='OtherTeamInfo.lableList', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='OtherTeamInfo.level', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experience', full_name='OtherTeamInfo.experience', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zhanli', full_name='OtherTeamInfo.zhanli', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registDate', full_name='OtherTeamInfo.registDate', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='club', full_name='OtherTeamInfo.club', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latelyLoginTime', full_name='OtherTeamInfo.latelyLoginTime', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leagueLevel', full_name='OtherTeamInfo.leagueLevel', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiantiRank', full_name='OtherTeamInfo.tiantiRank', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='achieveIcon1', full_name='OtherTeamInfo.achieveIcon1', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='achieveIcon2', full_name='OtherTeamInfo.achieveIcon2', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='achieveIcon3', full_name='OtherTeamInfo.achieveIcon3', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homeFieldPoloShirt', full_name='OtherTeamInfo.homeFieldPoloShirt', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitingFieldPoloShirt', full_name='OtherTeamInfo.visitingFieldPoloShirt', index=15,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherUserBattle', full_name='OtherTeamInfo.otherUserBattle', index=16,
      number=17, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='OtherTeamInfo.vipLevel', index=17,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guildName', full_name='OtherTeamInfo.guildName', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=512,
)

_OTHERTEAMINFO.fields_by_name['lableList'].message_type = managerLable__pb2._MANAGERLABLE
_OTHERTEAMINFO.fields_by_name['otherUserBattle'].message_type = otherUserBattle__pb2._OTHERUSERBATTLE
DESCRIPTOR.message_types_by_name['OtherTeamInfo'] = _OTHERTEAMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OtherTeamInfo = _reflection.GeneratedProtocolMessageType('OtherTeamInfo', (_message.Message,), dict(
  DESCRIPTOR = _OTHERTEAMINFO,
  __module__ = 'otherTeamInfo_pb2'
  # @@protoc_insertion_point(class_scope:OtherTeamInfo)
  ))
_sym_db.RegisterMessage(OtherTeamInfo)


# @@protoc_insertion_point(module_scope)
