# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otherUserBattle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gamePlayerInstance_pb2 as gamePlayerInstance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='otherUserBattle.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15otherUserBattle.proto\x1a\x18gamePlayerInstance.proto\"v\n\x0fOtherUserBattle\x12\x33\n\x16gamePlayerInstanceList\x18\x01 \x03(\x0b\x32\x13.GamePlayerInstance\x12\x13\n\x0b\x66ormationId\x18\x02 \x02(\x05\x12\x19\n\x11\x62\x61ttleArrayZhanli\x18\x03 \x02(\x05')
  ,
  dependencies=[gamePlayerInstance__pb2.DESCRIPTOR,])




_OTHERUSERBATTLE = _descriptor.Descriptor(
  name='OtherUserBattle',
  full_name='OtherUserBattle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gamePlayerInstanceList', full_name='OtherUserBattle.gamePlayerInstanceList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formationId', full_name='OtherUserBattle.formationId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battleArrayZhanli', full_name='OtherUserBattle.battleArrayZhanli', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=169,
)

_OTHERUSERBATTLE.fields_by_name['gamePlayerInstanceList'].message_type = gamePlayerInstance__pb2._GAMEPLAYERINSTANCE
DESCRIPTOR.message_types_by_name['OtherUserBattle'] = _OTHERUSERBATTLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OtherUserBattle = _reflection.GeneratedProtocolMessageType('OtherUserBattle', (_message.Message,), dict(
  DESCRIPTOR = _OTHERUSERBATTLE,
  __module__ = 'otherUserBattle_pb2'
  # @@protoc_insertion_point(class_scope:OtherUserBattle)
  ))
_sym_db.RegisterMessage(OtherUserBattle)


# @@protoc_insertion_point(module_scope)
