# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerZhanli.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='playerZhanli.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12playerZhanli.proto\"\xd3\x01\n\x0cPlayerZhanli\x12\x0e\n\x06shemen\x18\x01 \x01(\x05\x12\x10\n\x08\x63huanqiu\x18\x02 \x01(\x05\x12\x0e\n\x06pandai\x18\x03 \x01(\x05\x12\x0e\n\x06jiewei\x18\x04 \x01(\x05\x12\x11\n\tqiangduan\x18\x05 \x01(\x05\x12\x0f\n\x07\x64ingren\x18\x06 \x01(\x05\x12\r\n\x05pujiu\x18\x07 \x01(\x05\x12\r\n\x05\x63huji\x18\x08 \x01(\x05\x12\x0e\n\x06kaiqiu\x18\t \x01(\x05\x12\x0f\n\x07\x66\x61nying\x18\n \x01(\x05\x12\r\n\x05shiye\x18\x0b \x01(\x05\x12\x0f\n\x07zhanwei\x18\x0c \x01(\x05')
)




_PLAYERZHANLI = _descriptor.Descriptor(
  name='PlayerZhanli',
  full_name='PlayerZhanli',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shemen', full_name='PlayerZhanli.shemen', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chuanqiu', full_name='PlayerZhanli.chuanqiu', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pandai', full_name='PlayerZhanli.pandai', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jiewei', full_name='PlayerZhanli.jiewei', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qiangduan', full_name='PlayerZhanli.qiangduan', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dingren', full_name='PlayerZhanli.dingren', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pujiu', full_name='PlayerZhanli.pujiu', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chuji', full_name='PlayerZhanli.chuji', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kaiqiu', full_name='PlayerZhanli.kaiqiu', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fanying', full_name='PlayerZhanli.fanying', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shiye', full_name='PlayerZhanli.shiye', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zhanwei', full_name='PlayerZhanli.zhanwei', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['PlayerZhanli'] = _PLAYERZHANLI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerZhanli = _reflection.GeneratedProtocolMessageType('PlayerZhanli', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERZHANLI,
  __module__ = 'playerZhanli_pb2'
  # @@protoc_insertion_point(class_scope:PlayerZhanli)
  ))
_sym_db.RegisterMessage(PlayerZhanli)


# @@protoc_insertion_point(module_scope)
