# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerPveAim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='playerPveAim.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12playerPveAim.proto\"?\n\x0cPlayerPveAim\x12\x11\n\tsectionId\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x0e\n\x06\x63ustom\x18\x03 \x02(\x05')
)




_PLAYERPVEAIM = _descriptor.Descriptor(
  name='PlayerPveAim',
  full_name='PlayerPveAim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectionId', full_name='PlayerPveAim.sectionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PlayerPveAim.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom', full_name='PlayerPveAim.custom', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['PlayerPveAim'] = _PLAYERPVEAIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerPveAim = _reflection.GeneratedProtocolMessageType('PlayerPveAim', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPVEAIM,
  __module__ = 'playerPveAim_pb2'
  # @@protoc_insertion_point(class_scope:PlayerPveAim)
  ))
_sym_db.RegisterMessage(PlayerPveAim)


# @@protoc_insertion_point(module_scope)
