# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quiz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gameTeamInfo_pb2 as gameTeamInfo__pb2
import quizItem_pb2 as quizItem__pb2
import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='quiz.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nquiz.proto\x1a\x12gameTeamInfo.proto\x1a\x0equizItem.proto\x1a\x0epropResp.proto\"\x12\n\x10\x43\x32GS_GetQuitList\"/\n\x10GS2C_GetQuitList\x12\x1b\n\x08quizList\x18\x01 \x03(\x0b\x32\t.QuizItem\"!\n\x12\x43\x32GS_BuyQuizTicket\x12\x0b\n\x03num\x18\x01 \x02(\x05\"X\n\x12GS2C_BuyQuizTicket\x12#\n\x0cgameTeamInfo\x18\x01 \x02(\x0b\x32\r.GameTeamInfo\x12\x1d\n\x08propResp\x18\x02 \x02(\x0b\x32\x0b.PropRespVo\"4\n\tC2GS_Quiz\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06itemId\x18\x02 \x02(\x05\x12\x0b\n\x03num\x18\x03 \x02(\x05\"E\n\tGS2C_Quiz\x12\x17\n\x04item\x18\x01 \x02(\x0b\x32\t.QuizItem\x12\x1f\n\npropRespVo\x18\x02 \x02(\x0b\x32\x0b.PropRespVo\"\x10\n\x0e\x43\x32GS_GetMyQuiz\"d\n\x0eGS2C_GetMyQuiz\x12\x1b\n\x08quizList\x18\x01 \x03(\x0b\x32\t.QuizItem\x12\x12\n\nmonthlyWin\x18\x02 \x02(\x05\x12\x10\n\x08totalWin\x18\x03 \x02(\x05\x12\x0f\n\x07\x64ueTime\x18\x04 \x02(\t\" \n\x12\x43\x32GS_GetQuizReward\x12\n\n\x02id\x18\x01 \x02(\x05\"[\n\x12GS2C_GetQuizReward\x12\x1f\n\npropRespVo\x18\x01 \x02(\x0b\x32\x0b.PropRespVo\x12\x12\n\nmonthlyWin\x18\x02 \x02(\x05\x12\x10\n\x08totalWin\x18\x03 \x02(\x05')
  ,
  dependencies=[gameTeamInfo__pb2.DESCRIPTOR,quizItem__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,])




_C2GS_GETQUITLIST = _descriptor.Descriptor(
  name='C2GS_GetQuitList',
  full_name='C2GS_GetQuitList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=84,
)


_GS2C_GETQUITLIST = _descriptor.Descriptor(
  name='GS2C_GetQuitList',
  full_name='GS2C_GetQuitList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quizList', full_name='GS2C_GetQuitList.quizList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=133,
)


_C2GS_BUYQUIZTICKET = _descriptor.Descriptor(
  name='C2GS_BuyQuizTicket',
  full_name='C2GS_BuyQuizTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='C2GS_BuyQuizTicket.num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=168,
)


_GS2C_BUYQUIZTICKET = _descriptor.Descriptor(
  name='GS2C_BuyQuizTicket',
  full_name='GS2C_BuyQuizTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='GS2C_BuyQuizTicket.gameTeamInfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propResp', full_name='GS2C_BuyQuizTicket.propResp', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=258,
)


_C2GS_QUIZ = _descriptor.Descriptor(
  name='C2GS_Quiz',
  full_name='C2GS_Quiz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='C2GS_Quiz.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='C2GS_Quiz.itemId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='C2GS_Quiz.num', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=312,
)


_GS2C_QUIZ = _descriptor.Descriptor(
  name='GS2C_Quiz',
  full_name='GS2C_Quiz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='GS2C_Quiz.item', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='GS2C_Quiz.propRespVo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=383,
)


_C2GS_GETMYQUIZ = _descriptor.Descriptor(
  name='C2GS_GetMyQuiz',
  full_name='C2GS_GetMyQuiz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=401,
)


_GS2C_GETMYQUIZ = _descriptor.Descriptor(
  name='GS2C_GetMyQuiz',
  full_name='GS2C_GetMyQuiz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quizList', full_name='GS2C_GetMyQuiz.quizList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='monthlyWin', full_name='GS2C_GetMyQuiz.monthlyWin', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalWin', full_name='GS2C_GetMyQuiz.totalWin', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dueTime', full_name='GS2C_GetMyQuiz.dueTime', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=503,
)


_C2GS_GETQUIZREWARD = _descriptor.Descriptor(
  name='C2GS_GetQuizReward',
  full_name='C2GS_GetQuizReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='C2GS_GetQuizReward.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=537,
)


_GS2C_GETQUIZREWARD = _descriptor.Descriptor(
  name='GS2C_GetQuizReward',
  full_name='GS2C_GetQuizReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='GS2C_GetQuizReward.propRespVo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='monthlyWin', full_name='GS2C_GetQuizReward.monthlyWin', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalWin', full_name='GS2C_GetQuizReward.totalWin', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=630,
)

_GS2C_GETQUITLIST.fields_by_name['quizList'].message_type = quizItem__pb2._QUIZITEM
_GS2C_BUYQUIZTICKET.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
_GS2C_BUYQUIZTICKET.fields_by_name['propResp'].message_type = propResp__pb2._PROPRESPVO
_GS2C_QUIZ.fields_by_name['item'].message_type = quizItem__pb2._QUIZITEM
_GS2C_QUIZ.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
_GS2C_GETMYQUIZ.fields_by_name['quizList'].message_type = quizItem__pb2._QUIZITEM
_GS2C_GETQUIZREWARD.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['C2GS_GetQuitList'] = _C2GS_GETQUITLIST
DESCRIPTOR.message_types_by_name['GS2C_GetQuitList'] = _GS2C_GETQUITLIST
DESCRIPTOR.message_types_by_name['C2GS_BuyQuizTicket'] = _C2GS_BUYQUIZTICKET
DESCRIPTOR.message_types_by_name['GS2C_BuyQuizTicket'] = _GS2C_BUYQUIZTICKET
DESCRIPTOR.message_types_by_name['C2GS_Quiz'] = _C2GS_QUIZ
DESCRIPTOR.message_types_by_name['GS2C_Quiz'] = _GS2C_QUIZ
DESCRIPTOR.message_types_by_name['C2GS_GetMyQuiz'] = _C2GS_GETMYQUIZ
DESCRIPTOR.message_types_by_name['GS2C_GetMyQuiz'] = _GS2C_GETMYQUIZ
DESCRIPTOR.message_types_by_name['C2GS_GetQuizReward'] = _C2GS_GETQUIZREWARD
DESCRIPTOR.message_types_by_name['GS2C_GetQuizReward'] = _GS2C_GETQUIZREWARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2GS_GetQuitList = _reflection.GeneratedProtocolMessageType('C2GS_GetQuitList', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETQUITLIST,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetQuitList)
  ))
_sym_db.RegisterMessage(C2GS_GetQuitList)

GS2C_GetQuitList = _reflection.GeneratedProtocolMessageType('GS2C_GetQuitList', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETQUITLIST,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetQuitList)
  ))
_sym_db.RegisterMessage(GS2C_GetQuitList)

C2GS_BuyQuizTicket = _reflection.GeneratedProtocolMessageType('C2GS_BuyQuizTicket', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_BUYQUIZTICKET,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_BuyQuizTicket)
  ))
_sym_db.RegisterMessage(C2GS_BuyQuizTicket)

GS2C_BuyQuizTicket = _reflection.GeneratedProtocolMessageType('GS2C_BuyQuizTicket', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_BUYQUIZTICKET,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_BuyQuizTicket)
  ))
_sym_db.RegisterMessage(GS2C_BuyQuizTicket)

C2GS_Quiz = _reflection.GeneratedProtocolMessageType('C2GS_Quiz', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_QUIZ,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_Quiz)
  ))
_sym_db.RegisterMessage(C2GS_Quiz)

GS2C_Quiz = _reflection.GeneratedProtocolMessageType('GS2C_Quiz', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_QUIZ,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_Quiz)
  ))
_sym_db.RegisterMessage(GS2C_Quiz)

C2GS_GetMyQuiz = _reflection.GeneratedProtocolMessageType('C2GS_GetMyQuiz', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETMYQUIZ,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetMyQuiz)
  ))
_sym_db.RegisterMessage(C2GS_GetMyQuiz)

GS2C_GetMyQuiz = _reflection.GeneratedProtocolMessageType('GS2C_GetMyQuiz', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETMYQUIZ,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetMyQuiz)
  ))
_sym_db.RegisterMessage(GS2C_GetMyQuiz)

C2GS_GetQuizReward = _reflection.GeneratedProtocolMessageType('C2GS_GetQuizReward', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETQUIZREWARD,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetQuizReward)
  ))
_sym_db.RegisterMessage(C2GS_GetQuizReward)

GS2C_GetQuizReward = _reflection.GeneratedProtocolMessageType('GS2C_GetQuizReward', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETQUIZREWARD,
  __module__ = 'quiz_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetQuizReward)
  ))
_sym_db.RegisterMessage(GS2C_GetQuizReward)


# @@protoc_insertion_point(module_scope)
