# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruitClickResp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gamePlayerInstance_pb2 as gamePlayerInstance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recruitClickResp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16recruitClickResp.proto\x1a\x18gamePlayerInstance.proto\"\xa9\x01\n\x12RecruitClickRespVo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0f\n\x07\x64iamond\x18\x03 \x01(\x05\x12\x0c\n\x04\x63oin\x18\x04 \x01(\x05\x12\x14\n\x0cremainCdTime\x18\x05 \x01(\x05\x12\x17\n\x0fremainfreeCount\x18\x06 \x01(\x05\x12\'\n\nplayerList\x18\x08 \x03(\x0b\x32\x13.GamePlayerInstance')
  ,
  dependencies=[gamePlayerInstance__pb2.DESCRIPTOR,])




_RECRUITCLICKRESPVO = _descriptor.Descriptor(
  name='RecruitClickRespVo',
  full_name='RecruitClickRespVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RecruitClickRespVo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='RecruitClickRespVo.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diamond', full_name='RecruitClickRespVo.diamond', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin', full_name='RecruitClickRespVo.coin', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remainCdTime', full_name='RecruitClickRespVo.remainCdTime', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remainfreeCount', full_name='RecruitClickRespVo.remainfreeCount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerList', full_name='RecruitClickRespVo.playerList', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=222,
)

_RECRUITCLICKRESPVO.fields_by_name['playerList'].message_type = gamePlayerInstance__pb2._GAMEPLAYERINSTANCE
DESCRIPTOR.message_types_by_name['RecruitClickRespVo'] = _RECRUITCLICKRESPVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecruitClickRespVo = _reflection.GeneratedProtocolMessageType('RecruitClickRespVo', (_message.Message,), dict(
  DESCRIPTOR = _RECRUITCLICKRESPVO,
  __module__ = 'recruitClickResp_pb2'
  # @@protoc_insertion_point(class_scope:RecruitClickRespVo)
  ))
_sym_db.RegisterMessage(RecruitClickRespVo)


# @@protoc_insertion_point(module_scope)
