# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruitPlayerTag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recruitPlayerTag.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16recruitPlayerTag.proto\"1\n\x10RecruitPlayerTag\x12\x10\n\x08playerId\x18\x01 \x02(\x05\x12\x0b\n\x03tag\x18\x02 \x02(\x05')
)




_RECRUITPLAYERTAG = _descriptor.Descriptor(
  name='RecruitPlayerTag',
  full_name='RecruitPlayerTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='RecruitPlayerTag.playerId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='RecruitPlayerTag.tag', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['RecruitPlayerTag'] = _RECRUITPLAYERTAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecruitPlayerTag = _reflection.GeneratedProtocolMessageType('RecruitPlayerTag', (_message.Message,), dict(
  DESCRIPTOR = _RECRUITPLAYERTAG,
  __module__ = 'recruitPlayerTag_pb2'
  # @@protoc_insertion_point(class_scope:RecruitPlayerTag)
  ))
_sym_db.RegisterMessage(RecruitPlayerTag)


# @@protoc_insertion_point(module_scope)
