# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruitLable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import recruitPlayerTag_pb2 as recruitPlayerTag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recruitLable.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12recruitLable.proto\x1a\x16recruitPlayerTag.proto\"\xd9\x02\n\x0cRecruitLable\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x11\n\ttitleIcon\x18\x03 \x01(\x05\x12\x0c\n\x04icon\x18\x04 \x01(\x05\x12\x10\n\x08ruleIcon\x18\x05 \x01(\x05\x12\x11\n\tpriceType\x18\x06 \x01(\x05\x12\r\n\x05price\x18\x07 \x01(\x05\x12\x10\n\x08priceTen\x18\x08 \x01(\x05\x12\x0e\n\x06\x63\x64Time\x18\t \x01(\x05\x12\x11\n\tfreeCount\x18\n \x01(\x05\x12\x11\n\tstartTime\x18\x0b \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x0c \x01(\t\x12\x17\n\x0fremainfreeCount\x18\r \x01(\x05\x12\x14\n\x0cremainCdTime\x18\x0e \x01(\x05\x12\'\n\x0cplayerIdList\x18\x0f \x03(\x0b\x32\x11.RecruitPlayerTag\x12\x17\n\x0fprobabilityList\x18\x10 \x03(\x05\x12\x10\n\x08ruleText\x18\x11 \x01(\t')
  ,
  dependencies=[recruitPlayerTag__pb2.DESCRIPTOR,])




_RECRUITLABLE = _descriptor.Descriptor(
  name='RecruitLable',
  full_name='RecruitLable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RecruitLable.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='RecruitLable.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='titleIcon', full_name='RecruitLable.titleIcon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='RecruitLable.icon', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruleIcon', full_name='RecruitLable.ruleIcon', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priceType', full_name='RecruitLable.priceType', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='RecruitLable.price', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priceTen', full_name='RecruitLable.priceTen', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cdTime', full_name='RecruitLable.cdTime', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freeCount', full_name='RecruitLable.freeCount', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='RecruitLable.startTime', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='RecruitLable.endTime', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remainfreeCount', full_name='RecruitLable.remainfreeCount', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remainCdTime', full_name='RecruitLable.remainCdTime', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerIdList', full_name='RecruitLable.playerIdList', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probabilityList', full_name='RecruitLable.probabilityList', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruleText', full_name='RecruitLable.ruleText', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=392,
)

_RECRUITLABLE.fields_by_name['playerIdList'].message_type = recruitPlayerTag__pb2._RECRUITPLAYERTAG
DESCRIPTOR.message_types_by_name['RecruitLable'] = _RECRUITLABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecruitLable = _reflection.GeneratedProtocolMessageType('RecruitLable', (_message.Message,), dict(
  DESCRIPTOR = _RECRUITLABLE,
  __module__ = 'recruitLable_pb2'
  # @@protoc_insertion_point(class_scope:RecruitLable)
  ))
_sym_db.RegisterMessage(RecruitLable)


# @@protoc_insertion_point(module_scope)
