# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roundResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import teamResult_pb2 as teamResult__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roundResult.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11roundResult.proto\x1a\x10teamResult.proto\"\xc4\x01\n\x0bRoundResult\x12\x0f\n\x07matchId\x18\x01 \x02(\x05\x12\x11\n\tmatchType\x18\x02 \x02(\x05\x12\r\n\x05isEnd\x18\x03 \x01(\x08\x12\x12\n\nroundIndex\x18\x04 \x01(\x05\x12\x0f\n\x07keyInfo\x18\x05 \x01(\t\x12\x12\n\nallKeyInfo\x18\x06 \x01(\t\x12#\n\x0ehomeTeamResult\x18\x07 \x01(\x0b\x32\x0b.TeamResult\x12$\n\x0fvisitTeamResult\x18\x08 \x01(\x0b\x32\x0b.TeamResult')
  ,
  dependencies=[teamResult__pb2.DESCRIPTOR,])




_ROUNDRESULT = _descriptor.Descriptor(
  name='RoundResult',
  full_name='RoundResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchId', full_name='RoundResult.matchId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matchType', full_name='RoundResult.matchType', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isEnd', full_name='RoundResult.isEnd', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roundIndex', full_name='RoundResult.roundIndex', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyInfo', full_name='RoundResult.keyInfo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allKeyInfo', full_name='RoundResult.allKeyInfo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homeTeamResult', full_name='RoundResult.homeTeamResult', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitTeamResult', full_name='RoundResult.visitTeamResult', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=236,
)

_ROUNDRESULT.fields_by_name['homeTeamResult'].message_type = teamResult__pb2._TEAMRESULT
_ROUNDRESULT.fields_by_name['visitTeamResult'].message_type = teamResult__pb2._TEAMRESULT
DESCRIPTOR.message_types_by_name['RoundResult'] = _ROUNDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoundResult = _reflection.GeneratedProtocolMessageType('RoundResult', (_message.Message,), dict(
  DESCRIPTOR = _ROUNDRESULT,
  __module__ = 'roundResult_pb2'
  # @@protoc_insertion_point(class_scope:RoundResult)
  ))
_sym_db.RegisterMessage(RoundResult)


# @@protoc_insertion_point(module_scope)
