# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settleStory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import storyCheckpoint_pb2 as storyCheckpoint__pb2
import propResp_pb2 as propResp__pb2
import gameTeamInfo_pb2 as gameTeamInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settleStory.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11settleStory.proto\x1a\x15storyCheckpoint.proto\x1a\x0epropResp.proto\x1a\x12gameTeamInfo.proto\"\x8d\x01\n\x0bSettleStory\x12\r\n\x05stars\x18\x01 \x02(\x05\x12)\n\x0fstoryCheckpoint\x18\x02 \x01(\x0b\x32\x10.StoryCheckpoint\x12\x1f\n\npropRespVo\x18\x03 \x03(\x0b\x32\x0b.PropRespVo\x12#\n\x0cgameTeamInfo\x18\x04 \x02(\x0b\x32\r.GameTeamInfo')
  ,
  dependencies=[storyCheckpoint__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,gameTeamInfo__pb2.DESCRIPTOR,])




_SETTLESTORY = _descriptor.Descriptor(
  name='SettleStory',
  full_name='SettleStory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stars', full_name='SettleStory.stars', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storyCheckpoint', full_name='SettleStory.storyCheckpoint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='SettleStory.propRespVo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='SettleStory.gameTeamInfo', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=222,
)

_SETTLESTORY.fields_by_name['storyCheckpoint'].message_type = storyCheckpoint__pb2._STORYCHECKPOINT
_SETTLESTORY.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
_SETTLESTORY.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
DESCRIPTOR.message_types_by_name['SettleStory'] = _SETTLESTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettleStory = _reflection.GeneratedProtocolMessageType('SettleStory', (_message.Message,), dict(
  DESCRIPTOR = _SETTLESTORY,
  __module__ = 'settleStory_pb2'
  # @@protoc_insertion_point(class_scope:SettleStory)
  ))
_sym_db.RegisterMessage(SettleStory)


# @@protoc_insertion_point(module_scope)
