# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settleNewPlayerCareer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import newPlayerCareerChapter_pb2 as newPlayerCareerChapter__pb2
import newPlayerCareerCheckpoint_pb2 as newPlayerCareerCheckpoint__pb2
import teaminfoAndPropListResp_pb2 as teaminfoAndPropListResp__pb2
import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settleNewPlayerCareer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1bsettleNewPlayerCareer.proto\x1a\x1cnewPlayerCareerChapter.proto\x1a\x1fnewPlayerCareerCheckpoint.proto\x1a\x1dteaminfoAndPropListResp.proto\x1a\x0epropResp.proto\"\x89\x02\n\x15SettleNewPlayerCareer\x12\x42\n\x1aplayerCareerCheckpointInfo\x18\x01 \x01(\x0b\x32\x1e.NewPlayerCareerCheckpointInfo\x12<\n\x17playerCareerChapterInfo\x18\x02 \x01(\x0b\x32\x1b.NewPlayerCareerChapterInfo\x12=\n\x19teamInfoAndPropListRespVo\x18\x03 \x01(\x0b\x32\x1a.TeamInfoAndPropListRespVo\x12\x1f\n\npropRespVo\x18\x04 \x01(\x0b\x32\x0b.PropRespVo\x12\x0e\n\x06result\x18\x05 \x02(\x05')
  ,
  dependencies=[newPlayerCareerChapter__pb2.DESCRIPTOR,newPlayerCareerCheckpoint__pb2.DESCRIPTOR,teaminfoAndPropListResp__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,])




_SETTLENEWPLAYERCAREER = _descriptor.Descriptor(
  name='SettleNewPlayerCareer',
  full_name='SettleNewPlayerCareer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerCareerCheckpointInfo', full_name='SettleNewPlayerCareer.playerCareerCheckpointInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerCareerChapterInfo', full_name='SettleNewPlayerCareer.playerCareerChapterInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teamInfoAndPropListRespVo', full_name='SettleNewPlayerCareer.teamInfoAndPropListRespVo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='SettleNewPlayerCareer.propRespVo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='SettleNewPlayerCareer.result', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=407,
)

_SETTLENEWPLAYERCAREER.fields_by_name['playerCareerCheckpointInfo'].message_type = newPlayerCareerCheckpoint__pb2._NEWPLAYERCAREERCHECKPOINTINFO
_SETTLENEWPLAYERCAREER.fields_by_name['playerCareerChapterInfo'].message_type = newPlayerCareerChapter__pb2._NEWPLAYERCAREERCHAPTERINFO
_SETTLENEWPLAYERCAREER.fields_by_name['teamInfoAndPropListRespVo'].message_type = teaminfoAndPropListResp__pb2._TEAMINFOANDPROPLISTRESPVO
_SETTLENEWPLAYERCAREER.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['SettleNewPlayerCareer'] = _SETTLENEWPLAYERCAREER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettleNewPlayerCareer = _reflection.GeneratedProtocolMessageType('SettleNewPlayerCareer', (_message.Message,), dict(
  DESCRIPTOR = _SETTLENEWPLAYERCAREER,
  __module__ = 'settleNewPlayerCareer_pb2'
  # @@protoc_insertion_point(class_scope:SettleNewPlayerCareer)
  ))
_sym_db.RegisterMessage(SettleNewPlayerCareer)


# @@protoc_insertion_point(module_scope)
