# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settleRankedRace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gameRankedRace_pb2 as gameRankedRace__pb2
import propResp_pb2 as propResp__pb2
import gameTeamInfo_pb2 as gameTeamInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settleRankedRace.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16settleRankedRace.proto\x1a\x14gameRankedRace.proto\x1a\x0epropResp.proto\x1a\x12gameTeamInfo.proto\"\x8f\x01\n\x10SettleRankedRace\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\'\n\x0eGameRankedRace\x18\x02 \x01(\x0b\x32\x0f.GameRankedRace\x12\x1f\n\npropRespVo\x18\x03 \x03(\x0b\x32\x0b.PropRespVo\x12#\n\x0cgameTeamInfo\x18\x04 \x02(\x0b\x32\r.GameTeamInfo')
  ,
  dependencies=[gameRankedRace__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,gameTeamInfo__pb2.DESCRIPTOR,])




_SETTLERANKEDRACE = _descriptor.Descriptor(
  name='SettleRankedRace',
  full_name='SettleRankedRace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='SettleRankedRace.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GameRankedRace', full_name='SettleRankedRace.GameRankedRace', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVo', full_name='SettleRankedRace.propRespVo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='SettleRankedRace.gameTeamInfo', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=228,
)

_SETTLERANKEDRACE.fields_by_name['GameRankedRace'].message_type = gameRankedRace__pb2._GAMERANKEDRACE
_SETTLERANKEDRACE.fields_by_name['propRespVo'].message_type = propResp__pb2._PROPRESPVO
_SETTLERANKEDRACE.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
DESCRIPTOR.message_types_by_name['SettleRankedRace'] = _SETTLERANKEDRACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettleRankedRace = _reflection.GeneratedProtocolMessageType('SettleRankedRace', (_message.Message,), dict(
  DESCRIPTOR = _SETTLERANKEDRACE,
  __module__ = 'settleRankedRace_pb2'
  # @@protoc_insertion_point(class_scope:SettleRankedRace)
  ))
_sym_db.RegisterMessage(SettleRankedRace)


# @@protoc_insertion_point(module_scope)
