# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settleLegendChallenge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settleLegendChallenge.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1bsettleLegendChallenge.proto\x1a\x0epropResp.proto\"\xc5\x01\n\x15SettleLegendChallenge\x12\x0e\n\x06result\x18\x01 \x02(\x05\x12\x12\n\ncondition1\x18\x02 \x02(\x05\x12\x12\n\ncondition2\x18\x03 \x02(\x05\x12\x12\n\ncondition3\x18\x04 \x02(\x05\x12#\n\x0epropRespVoList\x18\x05 \x03(\x0b\x32\x0b.PropRespVo\x12\x0b\n\x03\x63up\x18\x06 \x02(\x05\x12\r\n\x05round\x18\x07 \x02(\x05\x12\x12\n\ncheckpoint\x18\x08 \x02(\x05\x12\x0b\n\x03max\x18\t \x02(\x05')
  ,
  dependencies=[propResp__pb2.DESCRIPTOR,])




_SETTLELEGENDCHALLENGE = _descriptor.Descriptor(
  name='SettleLegendChallenge',
  full_name='SettleLegendChallenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SettleLegendChallenge.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition1', full_name='SettleLegendChallenge.condition1', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition2', full_name='SettleLegendChallenge.condition2', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition3', full_name='SettleLegendChallenge.condition3', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVoList', full_name='SettleLegendChallenge.propRespVoList', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cup', full_name='SettleLegendChallenge.cup', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='SettleLegendChallenge.round', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint', full_name='SettleLegendChallenge.checkpoint', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='SettleLegendChallenge.max', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=245,
)

_SETTLELEGENDCHALLENGE.fields_by_name['propRespVoList'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['SettleLegendChallenge'] = _SETTLELEGENDCHALLENGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettleLegendChallenge = _reflection.GeneratedProtocolMessageType('SettleLegendChallenge', (_message.Message,), dict(
  DESCRIPTOR = _SETTLELEGENDCHALLENGE,
  __module__ = 'settleLegendChallenge_pb2'
  # @@protoc_insertion_point(class_scope:SettleLegendChallenge)
  ))
_sym_db.RegisterMessage(SettleLegendChallenge)


# @@protoc_insertion_point(module_scope)
