# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settleTourPve.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import teaminfoAndPropListResp_pb2 as teaminfoAndPropListResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settleTourPve.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13settleTourPve.proto\x1a\x1dteaminfoAndPropListResp.proto\"l\n\rSettleTourPve\x12\x0c\n\x04over\x18\x02 \x01(\x05\x12=\n\x19teamInfoAndPropListRespVo\x18\x01 \x01(\x0b\x32\x1a.TeamInfoAndPropListRespVo\x12\x0e\n\x06result\x18\x03 \x02(\x05')
  ,
  dependencies=[teaminfoAndPropListResp__pb2.DESCRIPTOR,])




_SETTLETOURPVE = _descriptor.Descriptor(
  name='SettleTourPve',
  full_name='SettleTourPve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='over', full_name='SettleTourPve.over', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teamInfoAndPropListRespVo', full_name='SettleTourPve.teamInfoAndPropListRespVo', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='SettleTourPve.result', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=162,
)

_SETTLETOURPVE.fields_by_name['teamInfoAndPropListRespVo'].message_type = teaminfoAndPropListResp__pb2._TEAMINFOANDPROPLISTRESPVO
DESCRIPTOR.message_types_by_name['SettleTourPve'] = _SETTLETOURPVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettleTourPve = _reflection.GeneratedProtocolMessageType('SettleTourPve', (_message.Message,), dict(
  DESCRIPTOR = _SETTLETOURPVE,
  __module__ = 'settleTourPve_pb2'
  # @@protoc_insertion_point(class_scope:SettleTourPve)
  ))
_sym_db.RegisterMessage(SettleTourPve)


# @@protoc_insertion_point(module_scope)
