# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import settleAd_pb2 as settleAd__pb2
import settleLegendChallenge_pb2 as settleLegendChallenge__pb2
import settlePlayerPve_pb2 as settlePlayerPve__pb2
import settleStory_pb2 as settleStory__pb2
import settleRankedRace_pb2 as settleRankedRace__pb2
import settleTourPve_pb2 as settleTourPve__pb2
import settlePracticeCompetition_pb2 as settlePracticeCompetition__pb2
import settleChampionRoad_pb2 as settleChampionRoad__pb2
import settleFriendlyMatch_pb2 as settleFriendlyMatch__pb2
import settleNewPlayerCareer_pb2 as settleNewPlayerCareer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settle.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0csettle.proto\x1a\x0esettleAd.proto\x1a\x1bsettleLegendChallenge.proto\x1a\x15settlePlayerPve.proto\x1a\x11settleStory.proto\x1a\x16settleRankedRace.proto\x1a\x13settleTourPve.proto\x1a\x1fsettlePracticeCompetition.proto\x1a\x18settleChampionRoad.proto\x1a\x19settleFriendlyMatch.proto\x1a\x1bsettleNewPlayerCareer.proto\"\xd7\x03\n\x06Settle\x12\x1b\n\x08settleAd\x18\x01 \x01(\x0b\x32\t.SettleAd\x12\x35\n\x15settleLegendChallenge\x18\x02 \x01(\x0b\x32\x16.SettleLegendChallenge\x12)\n\x0fsettlePlayerPve\x18\x03 \x01(\x0b\x32\x10.SettlePlayerPve\x12!\n\x0bsettleStory\x18\x04 \x01(\x0b\x32\x0c.SettleStory\x12+\n\x10settleRankedRace\x18\x05 \x01(\x0b\x32\x11.SettleRankedRace\x12%\n\rsettleTourPve\x18\x06 \x01(\x0b\x32\x0e.SettleTourPve\x12<\n\x18settlPracticeCompetition\x18\x07 \x01(\x0b\x32\x1a.SettlePracticeCompetition\x12/\n\x12settleChampionRoad\x18\x08 \x01(\x0b\x32\x13.SettleChampionRoad\x12\x31\n\x13settleFriendlyMatch\x18\t \x01(\x0b\x32\x14.SettleFriendlyMatch\x12\x35\n\x15settleNewPlayerCareer\x18\n \x01(\x0b\x32\x16.SettleNewPlayerCareer')
  ,
  dependencies=[settleAd__pb2.DESCRIPTOR,settleLegendChallenge__pb2.DESCRIPTOR,settlePlayerPve__pb2.DESCRIPTOR,settleStory__pb2.DESCRIPTOR,settleRankedRace__pb2.DESCRIPTOR,settleTourPve__pb2.DESCRIPTOR,settlePracticeCompetition__pb2.DESCRIPTOR,settleChampionRoad__pb2.DESCRIPTOR,settleFriendlyMatch__pb2.DESCRIPTOR,settleNewPlayerCareer__pb2.DESCRIPTOR,])




_SETTLE = _descriptor.Descriptor(
  name='Settle',
  full_name='Settle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='settleAd', full_name='Settle.settleAd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleLegendChallenge', full_name='Settle.settleLegendChallenge', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settlePlayerPve', full_name='Settle.settlePlayerPve', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleStory', full_name='Settle.settleStory', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleRankedRace', full_name='Settle.settleRankedRace', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleTourPve', full_name='Settle.settleTourPve', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settlPracticeCompetition', full_name='Settle.settlPracticeCompetition', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleChampionRoad', full_name='Settle.settleChampionRoad', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleFriendlyMatch', full_name='Settle.settleFriendlyMatch', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settleNewPlayerCareer', full_name='Settle.settleNewPlayerCareer', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=735,
)

_SETTLE.fields_by_name['settleAd'].message_type = settleAd__pb2._SETTLEAD
_SETTLE.fields_by_name['settleLegendChallenge'].message_type = settleLegendChallenge__pb2._SETTLELEGENDCHALLENGE
_SETTLE.fields_by_name['settlePlayerPve'].message_type = settlePlayerPve__pb2._SETTLEPLAYERPVE
_SETTLE.fields_by_name['settleStory'].message_type = settleStory__pb2._SETTLESTORY
_SETTLE.fields_by_name['settleRankedRace'].message_type = settleRankedRace__pb2._SETTLERANKEDRACE
_SETTLE.fields_by_name['settleTourPve'].message_type = settleTourPve__pb2._SETTLETOURPVE
_SETTLE.fields_by_name['settlPracticeCompetition'].message_type = settlePracticeCompetition__pb2._SETTLEPRACTICECOMPETITION
_SETTLE.fields_by_name['settleChampionRoad'].message_type = settleChampionRoad__pb2._SETTLECHAMPIONROAD
_SETTLE.fields_by_name['settleFriendlyMatch'].message_type = settleFriendlyMatch__pb2._SETTLEFRIENDLYMATCH
_SETTLE.fields_by_name['settleNewPlayerCareer'].message_type = settleNewPlayerCareer__pb2._SETTLENEWPLAYERCAREER
DESCRIPTOR.message_types_by_name['Settle'] = _SETTLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Settle = _reflection.GeneratedProtocolMessageType('Settle', (_message.Message,), dict(
  DESCRIPTOR = _SETTLE,
  __module__ = 'settle_pb2'
  # @@protoc_insertion_point(class_scope:Settle)
  ))
_sym_db.RegisterMessage(Settle)


# @@protoc_insertion_point(module_scope)
