# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teamChangingPlayers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teamChangingPlayers.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19teamChangingPlayers.proto\"v\n\x13TeamChangingPlayers\x12\x17\n\x0fisChangeOnField\x18\x01 \x01(\x05\x12\x13\n\x0bupPlayerIds\x18\x02 \x03(\x05\x12\x15\n\rdownPlayerIds\x18\x03 \x03(\x05\x12\x1a\n\x12totalDownPlayerIds\x18\x04 \x03(\x05')
)




_TEAMCHANGINGPLAYERS = _descriptor.Descriptor(
  name='TeamChangingPlayers',
  full_name='TeamChangingPlayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isChangeOnField', full_name='TeamChangingPlayers.isChangeOnField', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upPlayerIds', full_name='TeamChangingPlayers.upPlayerIds', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downPlayerIds', full_name='TeamChangingPlayers.downPlayerIds', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalDownPlayerIds', full_name='TeamChangingPlayers.totalDownPlayerIds', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['TeamChangingPlayers'] = _TEAMCHANGINGPLAYERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamChangingPlayers = _reflection.GeneratedProtocolMessageType('TeamChangingPlayers', (_message.Message,), dict(
  DESCRIPTOR = _TEAMCHANGINGPLAYERS,
  __module__ = 'teamChangingPlayers_pb2'
  # @@protoc_insertion_point(class_scope:TeamChangingPlayers)
  ))
_sym_db.RegisterMessage(TeamChangingPlayers)


# @@protoc_insertion_point(module_scope)
