# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teamClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gamePlayerBattle_pb2 as gamePlayerBattle__pb2
import gamePlayerInstance_pb2 as gamePlayerInstance__pb2
import gameUserTacticsInfo_pb2 as gameUserTacticsInfo__pb2
import gamePlayerResponsibility_pb2 as gamePlayerResponsibility__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teamClient.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10teamClient.proto\x1a\x16gamePlayerBattle.proto\x1a\x18gamePlayerInstance.proto\x1a\x19gameUserTacticsInfo.proto\x1a\x1egamePlayerResponsibility.proto\"\xf2\x01\n\nTeamClient\x12\x16\n\x07isRobot\x18\x01 \x01(\x08:\x05\x66\x61lse\x12+\n\x10gamePlayerBattle\x18\x02 \x01(\x0b\x32\x11.GamePlayerBattle\x12/\n\x12gamePlayerInstance\x18\x03 \x03(\x0b\x32\x13.GamePlayerInstance\x12\x31\n\x13gameUserTacticsInfo\x18\x04 \x02(\x0b\x32\x14.GameUserTacticsInfo\x12;\n\x18gamePlayerResponsibility\x18\x05 \x03(\x0b\x32\x19.GamePlayerResponsibility')
  ,
  dependencies=[gamePlayerBattle__pb2.DESCRIPTOR,gamePlayerInstance__pb2.DESCRIPTOR,gameUserTacticsInfo__pb2.DESCRIPTOR,gamePlayerResponsibility__pb2.DESCRIPTOR,])




_TEAMCLIENT = _descriptor.Descriptor(
  name='TeamClient',
  full_name='TeamClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isRobot', full_name='TeamClient.isRobot', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamePlayerBattle', full_name='TeamClient.gamePlayerBattle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamePlayerInstance', full_name='TeamClient.gamePlayerInstance', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameUserTacticsInfo', full_name='TeamClient.gameUserTacticsInfo', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamePlayerResponsibility', full_name='TeamClient.gamePlayerResponsibility', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=372,
)

_TEAMCLIENT.fields_by_name['gamePlayerBattle'].message_type = gamePlayerBattle__pb2._GAMEPLAYERBATTLE
_TEAMCLIENT.fields_by_name['gamePlayerInstance'].message_type = gamePlayerInstance__pb2._GAMEPLAYERINSTANCE
_TEAMCLIENT.fields_by_name['gameUserTacticsInfo'].message_type = gameUserTacticsInfo__pb2._GAMEUSERTACTICSINFO
_TEAMCLIENT.fields_by_name['gamePlayerResponsibility'].message_type = gamePlayerResponsibility__pb2._GAMEPLAYERRESPONSIBILITY
DESCRIPTOR.message_types_by_name['TeamClient'] = _TEAMCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamClient = _reflection.GeneratedProtocolMessageType('TeamClient', (_message.Message,), dict(
  DESCRIPTOR = _TEAMCLIENT,
  __module__ = 'teamClient_pb2'
  # @@protoc_insertion_point(class_scope:TeamClient)
  ))
_sym_db.RegisterMessage(TeamClient)


# @@protoc_insertion_point(module_scope)
