# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teamPlayerFormation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teamPlayerFormation.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19teamPlayerFormation.proto\"\xa9\x04\n\x13TeamPlayerFormation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nformatName\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x11\n\tplayerNum\x18\x04 \x01(\x05\x12\x0e\n\x06gridId\x18\x05 \x01(\x05\x12\x11\n\tposition1\x18\x06 \x01(\x05\x12\x11\n\tposition2\x18\x07 \x01(\x05\x12\x11\n\tposition3\x18\x08 \x01(\x05\x12\x11\n\tposition4\x18\t \x01(\x05\x12\x11\n\tposition5\x18\n \x01(\x05\x12\x11\n\tposition6\x18\x0b \x01(\x05\x12\x11\n\tposition7\x18\x0c \x01(\x05\x12\x11\n\tposition8\x18\r \x01(\x05\x12\x11\n\tposition9\x18\x0e \x01(\x05\x12\x12\n\nposition10\x18\x0f \x01(\x05\x12\x12\n\nposition11\x18\x10 \x01(\x05\x12\x12\n\nposition12\x18\x11 \x01(\x05\x12\x12\n\nposition13\x18\x12 \x01(\x05\x12\x12\n\nposition14\x18\x13 \x01(\x05\x12\x12\n\nposition15\x18\x14 \x01(\x05\x12\x12\n\nposition16\x18\x15 \x01(\x05\x12\x12\n\nposition17\x18\x16 \x01(\x05\x12\x12\n\nposition18\x18\x17 \x01(\x05\x12\x12\n\nposition19\x18\x18 \x01(\x05\x12\x12\n\nposition20\x18\x19 \x01(\x05\x12\x12\n\nposition21\x18\x1a \x01(\x05\x12\x12\n\nposition22\x18\x1b \x01(\x05\x12\x12\n\nposition23\x18\x1c \x01(\x05')
)




_TEAMPLAYERFORMATION = _descriptor.Descriptor(
  name='TeamPlayerFormation',
  full_name='TeamPlayerFormation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TeamPlayerFormation.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formatName', full_name='TeamPlayerFormation.formatName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='TeamPlayerFormation.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerNum', full_name='TeamPlayerFormation.playerNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gridId', full_name='TeamPlayerFormation.gridId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position1', full_name='TeamPlayerFormation.position1', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position2', full_name='TeamPlayerFormation.position2', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position3', full_name='TeamPlayerFormation.position3', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position4', full_name='TeamPlayerFormation.position4', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position5', full_name='TeamPlayerFormation.position5', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position6', full_name='TeamPlayerFormation.position6', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position7', full_name='TeamPlayerFormation.position7', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position8', full_name='TeamPlayerFormation.position8', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position9', full_name='TeamPlayerFormation.position9', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position10', full_name='TeamPlayerFormation.position10', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position11', full_name='TeamPlayerFormation.position11', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position12', full_name='TeamPlayerFormation.position12', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position13', full_name='TeamPlayerFormation.position13', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position14', full_name='TeamPlayerFormation.position14', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position15', full_name='TeamPlayerFormation.position15', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position16', full_name='TeamPlayerFormation.position16', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position17', full_name='TeamPlayerFormation.position17', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position18', full_name='TeamPlayerFormation.position18', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position19', full_name='TeamPlayerFormation.position19', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position20', full_name='TeamPlayerFormation.position20', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position21', full_name='TeamPlayerFormation.position21', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position22', full_name='TeamPlayerFormation.position22', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position23', full_name='TeamPlayerFormation.position23', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=583,
)

DESCRIPTOR.message_types_by_name['TeamPlayerFormation'] = _TEAMPLAYERFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamPlayerFormation = _reflection.GeneratedProtocolMessageType('TeamPlayerFormation', (_message.Message,), dict(
  DESCRIPTOR = _TEAMPLAYERFORMATION,
  __module__ = 'teamPlayerFormation_pb2'
  # @@protoc_insertion_point(class_scope:TeamPlayerFormation)
  ))
_sym_db.RegisterMessage(TeamPlayerFormation)


# @@protoc_insertion_point(module_scope)
