# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teamFormationGrid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teamFormationGrid.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17teamFormationGrid.proto\"\xc6\x01\n\x11TeamFormationGrid\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05grid1\x18\x02 \x01(\x05\x12\r\n\x05grid2\x18\x03 \x01(\x05\x12\r\n\x05grid3\x18\x04 \x01(\x05\x12\r\n\x05grid4\x18\x05 \x01(\x05\x12\r\n\x05grid5\x18\x06 \x01(\x05\x12\r\n\x05grid6\x18\x07 \x01(\x05\x12\r\n\x05grid7\x18\x08 \x01(\x05\x12\r\n\x05grid8\x18\t \x01(\x05\x12\r\n\x05grid9\x18\n \x01(\x05\x12\x0e\n\x06grid10\x18\x0b \x01(\x05\x12\x0e\n\x06grid11\x18\x0c \x01(\x05')
)




_TEAMFORMATIONGRID = _descriptor.Descriptor(
  name='TeamFormationGrid',
  full_name='TeamFormationGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TeamFormationGrid.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid1', full_name='TeamFormationGrid.grid1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid2', full_name='TeamFormationGrid.grid2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid3', full_name='TeamFormationGrid.grid3', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid4', full_name='TeamFormationGrid.grid4', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid5', full_name='TeamFormationGrid.grid5', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid6', full_name='TeamFormationGrid.grid6', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid7', full_name='TeamFormationGrid.grid7', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid8', full_name='TeamFormationGrid.grid8', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid9', full_name='TeamFormationGrid.grid9', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid10', full_name='TeamFormationGrid.grid10', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid11', full_name='TeamFormationGrid.grid11', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['TeamFormationGrid'] = _TEAMFORMATIONGRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamFormationGrid = _reflection.GeneratedProtocolMessageType('TeamFormationGrid', (_message.Message,), dict(
  DESCRIPTOR = _TEAMFORMATIONGRID,
  __module__ = 'teamFormationGrid_pb2'
  # @@protoc_insertion_point(class_scope:TeamFormationGrid)
  ))
_sym_db.RegisterMessage(TeamFormationGrid)


# @@protoc_insertion_point(module_scope)
