# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gameTeamInfo_pb2 as gameTeamInfo__pb2
import gameUserVipPackage_pb2 as gameUserVipPackage__pb2
import propResp_pb2 as propResp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vip.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tvip.proto\x1a\x12gameTeamInfo.proto\x1a\x18gameUserVipPackage.proto\x1a\x0epropResp.proto\"\x1a\n\x18\x43\x32GS_GetVipPackageStatus\"O\n\x18GS2C_GetVipPackageStatus\x12\x33\n\x16gameUserVipPackageList\x18\x01 \x03(\x0b\x32\x13.GameUserVipPackage\" \n\x12\x43\x32GS_BuyVipPackage\x12\n\n\x02id\x18\x01 \x02(\x05\"\x8f\x01\n\x12GS2C_BuyVipPackage\x12/\n\x12gameUserVipPackage\x18\x01 \x02(\x0b\x32\x13.GameUserVipPackage\x12#\n\x0epropRespVoList\x18\x02 \x03(\x0b\x32\x0b.PropRespVo\x12#\n\x0cgameTeamInfo\x18\x03 \x02(\x0b\x32\r.GameTeamInfo\"\x1a\n\x18\x43\x32GS_GetVipWelfareStatus\"O\n\x18GS2C_GetVipWelfareStatus\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12#\n\x0cgameTeamInfo\x18\x02 \x02(\x0b\x32\r.GameTeamInfo\"\x18\n\x16\x43\x32GS_ReceiveVipWelfare\"=\n\x16GS2C_ReceiveVipWelfare\x12#\n\x0epropRespVoList\x18\x01 \x03(\x0b\x32\x0b.PropRespVo')
  ,
  dependencies=[gameTeamInfo__pb2.DESCRIPTOR,gameUserVipPackage__pb2.DESCRIPTOR,propResp__pb2.DESCRIPTOR,])




_C2GS_GETVIPPACKAGESTATUS = _descriptor.Descriptor(
  name='C2GS_GetVipPackageStatus',
  full_name='C2GS_GetVipPackageStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=101,
)


_GS2C_GETVIPPACKAGESTATUS = _descriptor.Descriptor(
  name='GS2C_GetVipPackageStatus',
  full_name='GS2C_GetVipPackageStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameUserVipPackageList', full_name='GS2C_GetVipPackageStatus.gameUserVipPackageList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=182,
)


_C2GS_BUYVIPPACKAGE = _descriptor.Descriptor(
  name='C2GS_BuyVipPackage',
  full_name='C2GS_BuyVipPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='C2GS_BuyVipPackage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=216,
)


_GS2C_BUYVIPPACKAGE = _descriptor.Descriptor(
  name='GS2C_BuyVipPackage',
  full_name='GS2C_BuyVipPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameUserVipPackage', full_name='GS2C_BuyVipPackage.gameUserVipPackage', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propRespVoList', full_name='GS2C_BuyVipPackage.propRespVoList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='GS2C_BuyVipPackage.gameTeamInfo', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=362,
)


_C2GS_GETVIPWELFARESTATUS = _descriptor.Descriptor(
  name='C2GS_GetVipWelfareStatus',
  full_name='C2GS_GetVipWelfareStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=390,
)


_GS2C_GETVIPWELFARESTATUS = _descriptor.Descriptor(
  name='GS2C_GetVipWelfareStatus',
  full_name='GS2C_GetVipWelfareStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GS2C_GetVipWelfareStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameTeamInfo', full_name='GS2C_GetVipWelfareStatus.gameTeamInfo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=471,
)


_C2GS_RECEIVEVIPWELFARE = _descriptor.Descriptor(
  name='C2GS_ReceiveVipWelfare',
  full_name='C2GS_ReceiveVipWelfare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=497,
)


_GS2C_RECEIVEVIPWELFARE = _descriptor.Descriptor(
  name='GS2C_ReceiveVipWelfare',
  full_name='GS2C_ReceiveVipWelfare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propRespVoList', full_name='GS2C_ReceiveVipWelfare.propRespVoList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=560,
)

_GS2C_GETVIPPACKAGESTATUS.fields_by_name['gameUserVipPackageList'].message_type = gameUserVipPackage__pb2._GAMEUSERVIPPACKAGE
_GS2C_BUYVIPPACKAGE.fields_by_name['gameUserVipPackage'].message_type = gameUserVipPackage__pb2._GAMEUSERVIPPACKAGE
_GS2C_BUYVIPPACKAGE.fields_by_name['propRespVoList'].message_type = propResp__pb2._PROPRESPVO
_GS2C_BUYVIPPACKAGE.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
_GS2C_GETVIPWELFARESTATUS.fields_by_name['gameTeamInfo'].message_type = gameTeamInfo__pb2._GAMETEAMINFO
_GS2C_RECEIVEVIPWELFARE.fields_by_name['propRespVoList'].message_type = propResp__pb2._PROPRESPVO
DESCRIPTOR.message_types_by_name['C2GS_GetVipPackageStatus'] = _C2GS_GETVIPPACKAGESTATUS
DESCRIPTOR.message_types_by_name['GS2C_GetVipPackageStatus'] = _GS2C_GETVIPPACKAGESTATUS
DESCRIPTOR.message_types_by_name['C2GS_BuyVipPackage'] = _C2GS_BUYVIPPACKAGE
DESCRIPTOR.message_types_by_name['GS2C_BuyVipPackage'] = _GS2C_BUYVIPPACKAGE
DESCRIPTOR.message_types_by_name['C2GS_GetVipWelfareStatus'] = _C2GS_GETVIPWELFARESTATUS
DESCRIPTOR.message_types_by_name['GS2C_GetVipWelfareStatus'] = _GS2C_GETVIPWELFARESTATUS
DESCRIPTOR.message_types_by_name['C2GS_ReceiveVipWelfare'] = _C2GS_RECEIVEVIPWELFARE
DESCRIPTOR.message_types_by_name['GS2C_ReceiveVipWelfare'] = _GS2C_RECEIVEVIPWELFARE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2GS_GetVipPackageStatus = _reflection.GeneratedProtocolMessageType('C2GS_GetVipPackageStatus', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETVIPPACKAGESTATUS,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetVipPackageStatus)
  ))
_sym_db.RegisterMessage(C2GS_GetVipPackageStatus)

GS2C_GetVipPackageStatus = _reflection.GeneratedProtocolMessageType('GS2C_GetVipPackageStatus', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETVIPPACKAGESTATUS,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetVipPackageStatus)
  ))
_sym_db.RegisterMessage(GS2C_GetVipPackageStatus)

C2GS_BuyVipPackage = _reflection.GeneratedProtocolMessageType('C2GS_BuyVipPackage', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_BUYVIPPACKAGE,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_BuyVipPackage)
  ))
_sym_db.RegisterMessage(C2GS_BuyVipPackage)

GS2C_BuyVipPackage = _reflection.GeneratedProtocolMessageType('GS2C_BuyVipPackage', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_BUYVIPPACKAGE,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_BuyVipPackage)
  ))
_sym_db.RegisterMessage(GS2C_BuyVipPackage)

C2GS_GetVipWelfareStatus = _reflection.GeneratedProtocolMessageType('C2GS_GetVipWelfareStatus', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_GETVIPWELFARESTATUS,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_GetVipWelfareStatus)
  ))
_sym_db.RegisterMessage(C2GS_GetVipWelfareStatus)

GS2C_GetVipWelfareStatus = _reflection.GeneratedProtocolMessageType('GS2C_GetVipWelfareStatus', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_GETVIPWELFARESTATUS,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_GetVipWelfareStatus)
  ))
_sym_db.RegisterMessage(GS2C_GetVipWelfareStatus)

C2GS_ReceiveVipWelfare = _reflection.GeneratedProtocolMessageType('C2GS_ReceiveVipWelfare', (_message.Message,), dict(
  DESCRIPTOR = _C2GS_RECEIVEVIPWELFARE,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:C2GS_ReceiveVipWelfare)
  ))
_sym_db.RegisterMessage(C2GS_ReceiveVipWelfare)

GS2C_ReceiveVipWelfare = _reflection.GeneratedProtocolMessageType('GS2C_ReceiveVipWelfare', (_message.Message,), dict(
  DESCRIPTOR = _GS2C_RECEIVEVIPWELFARE,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:GS2C_ReceiveVipWelfare)
  ))
_sym_db.RegisterMessage(GS2C_ReceiveVipWelfare)


# @@protoc_insertion_point(module_scope)
